### ISSUE TITLE
METRO Houston GTFS page isn't updating

### ISSUE THREAD

**Issue by colinmcglynn** [TransitFeeds/TransitFeeds-Public#102]
The METRO Houston GTFS http://transitfeeds.com/p/metro/25 page isn't updating with the latest GTFS for the agency, even though the [Offical Download Link](http://www.ridemetro.org/Downloads/google_transit.zip) included on the page is correct and has the latest GTFS.

**Comment by HendX** [comment]
Thanks @colinmcglynn, I'm not sure exactly why this happened. TransitFeeds checks for updates based on the previously saved version and received a "304 Not Modified".

**Comment by HendX** [comment]
(I forgot to include: The feed is updated now, and hopefully it continues to update)
