### ISSUE TITLE
Bilbao, Spain

### ISSUE THREAD

**Issue by joriswu** [TransitFeeds/TransitFeeds-Public#113]
Bilbao and regional services by Bizkaibus is here

ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/Bizkaibus/google_transit.zip

Coverage map is here

http://apli.bizkaia.net/apps/danok/tq/index.html?Idioma=EU

Bilbobus is here

ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/Bilbobus/google_transit.zip

**Comment by mldickens** [comment]
I added a bunch of feeds from this website:
http://transitfeeds.com/l/484-bilbao-biscay-spain
