### ISSUE TITLE
Caltrain missing shapefiles

### ISSUE THREAD

**Issue by adampitchie** [TransitFeeds/TransitFeeds-Public#120]
The zips for all the latest caltrain files are missing the shape files. Any solution to this? Perhaps since it's the same shape, add the old shape file to the zip?

**Comment by HendX** [comment]
I'm not sure what to do about this @adampitchie since they're not in the source GTFS.

**Comment by rupey** [comment]
Caltrain's developer page says "The Caltrain GTFS file is temporarily suspended as we work out some bugs. We apologize to our loyal developer community and hope to get a workable file to you as soon as we can."
