### ISSUE TITLE
Update for grand-river-transit/203

### ISSUE THREAD

**Issue by gboudreau** [TransitFeeds/TransitFeeds-Public#121]
Three files are listed on their GTFS page (for which you have the right URL):
http://www.regionofwaterloo.ca/opendatadownloads/GRT_Merged_GTFS.zip
http://www.regionofwaterloo.ca/opendatadownloads/GRT_GTFS.zip
http://www.regionofwaterloo.ca/opendatadownloads/GRT_Daily_GTFS.zip

The first does not have the spring schedules, while the other 2 do. I suggest using the second as the official source, since they say it is published 3 weeks in advance.
If it's possible to use multiple URLs as the source, I would also add the 3rd into that list, since that one will contain changes that can occur during the periods, while the first two are only published once.

**Comment by HendX** [comment]
Thanks - refer to #127, where I've just fixed that and added GTFS-realtime feeds.
