### ISSUE TITLE
ADD Cuneo GTFS

### ISSUE THREAD

**Issue by stebazzi** [TransitFeeds/TransitFeeds-Public#122]
Please add the feed of city Cuneo and Province
http://opendata.5t.torino.it/gtfs/cuneo_it.zip
Many thanks

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/cuneo/622

**Comment by fede843** [comment]
Hi @stebazzi seems like Cuneo bundle is outdated since a while (July 2017). Do you now if there is any plans on updating it?
Cheers!

**Comment by stebazzi** [comment]
Hello, I wrote the new link at the issue #189 (gtfs Piemonte).It’s still open.

I don’t know what’s the update frequency.

Unfortunately I have noticed that transitfeeds hasn’t add new feeds since november. The last one was RTA and the queue for the new additions is increasing more and more

What’s happening to transitfeeds.org?

 

Cheers!!

 

Da: Federico Vidaurreta [mailto:notifications@github.com] 
Inviato: mercoledì 17 gennaio 2018 17:03
A: TransitFeeds/TransitFeeds-Public <TransitFeeds-Public@noreply.github.com>
Cc: stebazzi <stebazzi@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [TransitFeeds/TransitFeeds-Public] ADD Cuneo GTFS (#122)

 

Hi @stebazzi <https://github.com/stebazzi>  seems like Cuneo bundle is outdated since a while (July 2017). Do you now if there is any plans on updating it?
Cheers!
