### ISSUE TITLE
ADD GTFS Venice

### ISSUE THREAD

**Issue by stebazzi** [TransitFeeds/TransitFeeds-Public#123]
Please add these Feeds about pubblic transport in Venice.
http://actv.avmspa.it/sites/default/files/attachments/opendata/automobilistico/actv_aut.zip
and
http://actv.avmspa.it/sites/default/files/attachments/opendata/navigazione/actv_nav.zip

Many Thanks

**Comment by HendX** [comment]
Thanks! I've added them here: https://transitfeeds.com/p/actv

I found it difficult to determine the name of the data provider and feed. Please let me know if the values I've chosen could be improved.

**Comment by stebazzi** [comment]
The provider name is the same name of Agency.
ACTV S.p.A.
Thank you
