### ISSUE TITLE
Official Grand River Transit (GRT) Feeds

### ISSUE THREAD

**Issue by grtdata** [TransitFeeds/TransitFeeds-Public#127]
**Static GTFS**: 
- http://www.regionofwaterloo.ca/opendatadownloads/GRT_GTFS.zip

**GTFS-realtime**: 
- http://192.237.29.212:8080/gtfsrealtime/VehiclePositions
- http://192.237.29.212:8080/gtfsrealtime/TripUpdates 

**License**:
- http://www.regionofwaterloo.ca/en/regionalGovernment/OpenDataLicence.asp

**Comment by HendX** [comment]
Thanks! I've updated the GTFS feed and added the GTFS-realtime feeds.

https://transitfeeds.com/p/grand-river-transit
