### ISSUE TITLE
Auckland Transport now has GTFS-realtime

### ISSUE THREAD

**Issue by araichev** [TransitFeeds/TransitFeeds-Public#130]
Auckland Transport, listed at http://transitfeeds.com/p/auckland-transport, has been publishing GTFS-realtime feeds since January.
The data is accessible from https://api.at.govt.nz/ but requires signing up for a free API key.
Would be useful to include the GTFS-realtime on TransitFeeds.

**Comment by HendX** [comment]
Thanks @araichev - I've added it the vehicle positions and trip updates feeds here: http://transitfeeds.com/p/auckland-transport

Note that they do offer a single combined feed of both, but I think splitting it out is good practice so I've used the separate ones instead.
