### ISSUE TITLE
New link for GTFS Turin

### ISSUE THREAD

**Issue by stebazzi** [TransitFeeds/TransitFeeds-Public#131]
Please, change the source link of GTFS in Turin (https://transitfeeds.com/p/gruppo-torinese-trasporti)
This one has routes of railway.

http://opendata.5t.torino.it/gtfs/torino_it+SFM.zip

Thanks

**Comment by mldickens** [comment]
I added the rail-only file (in that same directory on the site) as a separate feed:
https://transitfeeds.com/p/gruppo-torinese-trasporti/664

**Comment by stebazzi** [comment]
That's ok, many thanks
