### ISSUE TITLE
Would be clearer to have a 'Download' button for GTFS-realtime similar to that of GTFS 

### ISSUE THREAD

**Issue by araichev** [TransitFeeds/TransitFeeds-Public#132]
A comment on user experience.
I wanted to download a particular GTFS-realtime feed and it took me a while to realize that i can do that through the 'Feed Source' option.
I think it would be clearer to relabel that option as 'Download' and maybe make it a button, thereby paralleling the structure of GTFS feed pages.

**Comment by HendX** [comment]
Thanks for the suggestion - the problem is that GTFS-realtime data changes extremely frequency (e.g. 5-15 seconds), and the site doesn't archive this data.

It's possible to view the current snapshot, which is taken hourly.
