### ISSUE TITLE
Montgomery County Ride On

### ISSUE THREAD

**Issue by colinmcglynn** [TransitFeeds/TransitFeeds-Public#134]
http://transitfeeds.com/p/montgomery-county-department-of-transportation/235

TransitFeeeds is currently pointing to the archived GTFS Data Exchange.

The county has moved the archive page here http://www.montgomerycountymd.gov/DOT-Transit/GTFS/GTFSfiles.html

The link for the current file is http://www.montgomerycountymd.gov/DOT-Transit/Resources/Files/RideOnGTFS.zip

**Comment by mldickens** [comment]
Thanks. I've updated it.
