### ISSUE TITLE
GTFS feed for Nice,France, Lignes d'Azur - found on http://opendata.nicecotedazur.org

### ISSUE THREAD

**Issue by mkosmach** [TransitFeeds/TransitFeeds-Public#139]
Page with feed: http://opendata.nicecotedazur.org/data/dataset/export-au-format-gtfs-du-reseau-de-transport-lignes-d-azur

Feed: http://opendata.nicecotedazur.org/data/dataset/export-au-format-gtfs-du-reseau-de-transport-lignes-d-azur/resource/aacb4eea-d008-4b13-b17a-848b8ced7e03/download

**Comment by HendX** [comment]
Thanks @mkosmach - sorry for the delay.

It's been added here:
https://transitfeeds.com/p/lignes-dazur/738
