### ISSUE TITLE
Birmingham, Alabama

### ISSUE THREAD

**Issue by line72** [TransitFeeds/TransitFeeds-Public#141]
The Birmingham-Jefferson County Transit Authority has been uploading their data to gtfs-data-exchange.com

The latest version is available here:

http://gtfs.s3.amazonaws.com/birmingham-jefferson-county-transit-authority_20151217_1948.zip

More information about the agency is available here:

http://www.gtfs-data-exchange.com/agency/birmingham-jefferson-county-transit-authority/
AND
http://www.bjcta.org

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/birmingham-jefferson-county-transit-authority/683
