### ISSUE TITLE
WMATA warnings content are blank

### ISSUE THREAD

**Issue by colinmcglynn** [TransitFeeds/TransitFeeds-Public#143]
The main page for WMATA shows that there are 3 Warnings, but the issues page shows blank alerts.
I'm guessing that the blank alerts are for the extraneous files in the bundle too_fast.txt and route_xref.txt.

![screen shot 2016-06-02 at 5 39 01 pm](https://cloud.githubusercontent.com/assets/4335814/15761961/2f702f78-28e9-11e6-981b-df379283eb4e.png)

http://transitfeeds.com/p/wmata/75/latest/issues

**Comment by HendX** [comment]
Thanks @colinmcglynn - I've reengineered how the whole backend processing works on the site, so it looks like it's from that. Will investigate soon.

**Comment by HendX** [comment]
This should be fixed now for any new feeds that are processed.
