### ISSUE TITLE
Durham Region Transit issue

### ISSUE THREAD

**Issue by danmackay** [TransitFeeds/TransitFeeds-Public#145]
Its currently impossible to view the details of a trip due to the site throwing out a 404 error for whatever reason

See: http://transitfeeds.com/p/durham-region-transit/642/latest/trip/[@2.0.1502385@][5][1380742997905]/2__4283

**Comment by HendX** [comment]
Thanks @danmackay. Looks like this is caused by the slash in the trip ID. Will investigate a fix.

**Comment by HendX** [comment]
Fixed.

**Comment by danmackay** [comment]
This issue seems to have returned

**Comment by HendX** [comment]
Sorry about this @danmackay - I've fixed it again.
