### ISSUE TITLE
Trafiklab Sweden update

### ISSUE THREAD

**Issue by tengl** [TransitFeeds/TransitFeeds-Public#146]
Hi, 
Please update URL for Sweden feed. The old will expire in august. 
New URL https://api.resrobot.se/gtfs/sweden.zip?key=<apikey>
I think that you need a new apikey.
https://www.trafiklab.se/api/gtfs-sverige-2-beta/gtfs-sverige-2

**Comment by HendX** [comment]
Thanks - will update before the old one expires.

**Comment by fede843** [comment]
Hello, I've tried to switch from V1 to V2 but found these 1501 routes. They are listed as "Communal Taxi Service" in https://support.google.com/transitpartners/answer/3520902. Whole 1500 type is under Taxi category. Could someone explain me what they represent? I've traced back many data set's routes flagged as 1501, and in their web sites they look like buses to me. Maybe it's a wrong usage issue. But I'd like to clarify what that type means.

Cheers,
Federico V.

**Comment by tengl** [comment]
Hi, I'm not sure. I will try to find out and update this thread it I get an answer.

**Comment by tengl** [comment]
Hi, sorry for the late update, I've been away from work. 

Anyway, communal taxi service is a service where you call for a taxi or bus and then they will run the normal route (I think). So the trip is scheduled by request. 

Not sure if the routes are tagged correctly in the Swedish feed.

**Comment by fede843** [comment]
Hello, thanks for the information. Appreciate it. I'll see how we can handle those.
Cheers!

**Comment by HendX** [comment]
The feed has been updated on TransitFeeds so I'm closing this issue.
