### ISSUE TITLE
GTFS Data for WheelsBus

### ISSUE THREAD

**Issue by HenryW95** [TransitFeeds/TransitFeeds-Public#148]
WheelsBus (East Bay Area) has a [developers page with GTFS information](http://www.wheelsbus.com/about/developers/). It would be great to get it on the TransitFeeds site!

**Comment by mldickens** [comment]
I've added it:
http://transitfeeds.com/p/livermore-amador-valley-transit-authority/701

**Comment by HenryW95** [comment]
Thanks a lot!!
