### ISSUE TITLE
Netherlands

### ISSUE THREAD

**Issue by kemkim** [TransitFeeds/TransitFeeds-Public#150]
This is a GTFS feed with transit data for virtually all bus/metro/train/tram and some ferry services in the Netherlands, it also contains most international connections towards Belgium, France, Germany and the UK. The feed is licensed under CC0 license without tedious constraints about what you can do with the data. The transit data used is supplied by transit agencies via the legally sanctioned "OpenGeo ND-OV loket", in a transmodel derived format. The transmodel-data is then converted by us in to GTFS. Some technical details: the feed contains shapes for most operators and we've developed a workflow that generate shapes for all rail, tram and metro lines when missing. Currently the stop-locations are directly set by the operator but we're going to switch over to the IFOPT data-set when that becomes available. We're also looking to incorporate fare information, but we're currently constrained by both the unavailability of this data and the lack of suitable structure in GTFS to model the fare-structure in the Netherlands. We're optimistic about the availability of fare information changing and the flexibility of GTFS. The feed also contains transfer information supplied by Dutch railways about trip-to-trip transfers, indicating whether a transfer is (im)possible on trip-to-trip detail. 

http://gtfs.ovapi.nl/nl/gtfs-nl.zip

https://datahub.io/dataset/gtfs-nl

**Comment by HendX** [comment]
Thanks - we've been wanting to add this but the servers needed some improvements due to their size.

I've now added all the feeds here:
https://transitfeeds.com/p/ov
