### ISSUE TITLE
Thousand Oaks Transit GTFS

### ISSUE THREAD

**Issue by christrillium** [TransitFeeds/TransitFeeds-Public#151]
http://data.trilliumtransit.com/gtfs/thousandoaks-ca-us/thousandoaks-ca-us.zip

**Comment by fede843** [comment]
Hi. What's the difference with GTFS found here http://www.toaks.org/government/depts/public_works/transit/google_transit.asp? I've compared both and clearly represent the same operator, but totally different sources.

**Comment by christrillium** [comment]
We recently updated their GTFS for them. The Trillium dataset is for sure the most recent. I'm not sure if they've included this updated version on their website as of yet.

**Comment by fede843** [comment]
great! Thanks!

**Comment by HendX** [comment]
Thanks @christrillium and @fede843, added here: https://transitfeeds.com/p/thousand-oaks-transit
