### ISSUE TITLE
Error:  Southbound Hwy 99 at Pemberton Creek Bridge

### ISSUE THREAD

**Issue by PembertonGateway** [TransitFeeds/TransitFeeds-Public#153]
Wrong Name  "102841. Southbound Hwy 99 at Pemberton Creek Bridge"

Correct Name "Southbound Hwy 99 at Pemberton Creekside (Stop ID: 102841)"  (<< Proper name WITHOUT " Bridge") exists 2 blocks south of mapped position 
 The bus stop is clearly visible on Satellite Google & Street View but is at stated position.Listed position 2 blocks North is false there is nothing there!! look yourself. 7261 British Columbia 99, Pemberton V0N 2L1 50.314003, -122.806268

https://www.google.ca/maps/search/Southbound+Hwy+99+at+Pemberton+Creekside/@50.3140913,-122.8064059,275m/data=!3m1!1e3
https://www.google.ca/maps/@50.3138404,-122.8061882,3a,75y,279.75h,76.36t/data=!3m6!1e1!3m4!1s_q9vpwoTj_OaPYKTFLKYMw!2e0!7i13312!8i6656

Correct Name " Northbound Hwy 99 at Pemberton Creek Bridge (Stop ID:102839)"visible on Street view Bus stop sign mounted on lamp post opposite to entrance to Creekside Pemberton,  & opposite of Park Street turn off. 7262 British Columbia 99, Pemberton, BC V0N 2L1. 50.314771, -122.805528
off.https://www.google.ca/maps/@50.3146818,-122.8057123,3a,75y,116.26h,82.52t/data=!3m6!1e1!3m4!1sd-bPVgUjGFt0BOsdV8tRjA!2e0!7i13312!8i6656

**Comment by HendX** [comment]
Hi @PembertonGateway - which feed are you referring to? You may need to contact the data provider in order to have this fixed, as TransitFeeds just aggregates their data.
