### ISSUE TITLE
GTFS-realtime feeds only

### ISSUE THREAD

**Issue by codekitchen-ws** [TransitFeeds/TransitFeeds-Public#156]
Is there a way to only search against realtime feeds? Can I retrieve a list of only realtime feeds?

**Comment by fede843** [comment]
that would be usefull

**Comment by araichev** [comment]
+1

**Comment by HendX** [comment]
It's a bit of a hidden feature, but try this:

https://transitfeeds.com/search?q=gtfsrt

**Comment by fede843** [comment]
Sweet, thanks!

**Comment by codekitchen-ws** [comment]
Perfect, thanks
