### ISSUE TITLE
Getting JSONs

### ISSUE THREAD

**Issue by deadanger** [TransitFeeds/TransitFeeds-Public#16]
Hello developers,
I'm a Android novice developer and I have been trying to find a way to get all bus stops given a bus route. I happened to find this site which appears very useful. But how do I get the files? I can't find the feed id anywhere. Also, can I get each file seperately instead of in a bundle zip? As in one url for one file (i.e. route.txt)

**Comment by HendX** [comment]
Hi there - at this stage the API only allows you to download the full GTFS zip file, which you can then process into the format you require for your app.

We're working on some new features that'll let you browse the feeds through the web site. Also, you can now view individual files through the web site (but not API).

For download the latest feed version from the API, the bundle ID can be determined by the URL. For example, the bundle ID of the feed at [http://transitfeeds.com/p/adelaide-metro/1](http://transitfeeds.com/p/adelaide-metro/1) feed is `adelaide-metro/1`
