### ISSUE TITLE
Feature request: improve API output readability

### ISSUE THREAD

**Issue by araichev** [TransitFeeds/TransitFeeds-Public#161]
Hi folks, i been testing your API today and was wondering if you could improve the human-readability of your response data by assigning verbose names to your keys. 
For example, calling ``getFeedVersions`` for Bundaberg, Australia returns a response that begins

    {'results': {'limit': 10,
      'numPages': 1,
      'page': 1,
      'total': 9,
      'versions': [{'f': {'id': 'translink/6',
         'l': {'id': 13,
          'lat': -24.864963,
          'lng': 152.348653,
          'n': 'Bundaberg',
          'pid': 9,
          't': 'Bundaberg QLD 4670, Australia'},
         't': 'Bundaberg GTFS',
         'u': {'d': 'http://translink.com.au/sites/default/files/assets/resources/about-translink/reporting-and-publications/open-data/gtfs/bundaberg.zip',
          'i': 'http://translink.com.au/about-translink/reporting-and-publications/public-transport-performance-data'}},
        'id': 'translink/6/20160623',
        'size': 140072,
        'ts': 1466720307,
        'url': 'https://transitfeeds.com/p/translink/6/20160623/download'},

I think it would be easier for humans to read and hence easier for programmers handle if you could replace 'f' with 'feed', 'l' with 'location', 'n' with 'name', etc. 
What do you think?

**Comment by HendX** [comment]
Hi Alex

Thanks for the feedback. This was done deliberately to reduce the amount of data across the wire. I agree though the documentation could be improved.

**Comment by HendX** [comment]
Hi @araichev, we've made improvements to the API docs here:

https://transitfeeds.com/api/

It's fully documented in Swagger format now. You can try calls here:

https://transitfeeds.com/api/swagger/

Or view the raw spec here:

https://transitfeeds.com/api/transitfeeds-api.yaml
