### ISSUE TITLE
Long Beach, CA - Long Beach Transit - GTFS Feed

### ISSUE THREAD

**Issue by ykhouja** [TransitFeeds/TransitFeeds-Public#163]
Hi, 

Here's is update for our new service change for June, and August 2016; 
https://lbtransit.box.com/shared/static/a29r6bewfz8xnxjyd9w16orcz4d0zect.zip

**Comment by HendX** [comment]
HI @ykhouja,

At this time we create and manage the feeds manually (hopefully in the near future it'll be opened up to agencies to manage their own listings).

The best way to keep your feed up to date is to supply a a URL that doesn't change between versions - that was TransitFeeds will auto-update when you modify the file.

That URL looks like it will change, so for now I will add it, but when there's an update, please update this ticket with a static URL.

(If the URL changes each time, it's more manually handling for us, and the data will update more slowly).

Thanks!

Quentin

**Comment by ykhouja** [comment]
I created this static link: https://lbtransit.box.com/shared/static/aoyeskwmsa9g7pyg78q3xuioi0lgqe4f.zip

You can use it, and I will update the files with same link

Thanks,
Yaser

**Comment by HendX** [comment]
Excellent - thanks. Closing this issue. Feed has been added here:

https://transitfeeds.com/p/long-beach-transit
