### ISSUE TITLE
Official feed link for AMAT Palermo (IT)

### ISSUE THREAD

**Issue by patperu** [TransitFeeds/TransitFeeds-Public#165]
Hello,
please add this link:
https://www.comune.palermo.it/gtfs/amat_feed_gtfs.zip

Thank you!

reference: https://github.com/openamat/Official-Data/issues/16

**Comment by HendX** [comment]
Thanks - this was already listed here:

https://transitfeeds.com/p/amat-palermo-spa/540

I've updated the URL though to reflect that new URL.
