### ISSUE TITLE
official gtfs Municipality of Lecce (ITALY)

### ISSUE THREAD

**Issue by piersoft** [TransitFeeds/TransitFeeds-Public#166]
http://dati.comune.lecce.it/dataset/trasporto-pubblico-locale/resource/ee823cd7-e3ef-489f-a711-cd55c8bb1315

**Comment by HendX** [comment]
Thanks @piersoft, I've added it here:

https://transitfeeds.com/p/societa-gestione-multipla-spa

(It may take a few minutes before it appears)
