### ISSUE TITLE
New feed: anaheim-ca-us (USA)

### ISSUE THREAD

**Issue by aaronantrim** [TransitFeeds/TransitFeeds-Public#17]
Public, official GTFS data for **Anaheim Resort Transportation** here:
http://data.trilliumtransit.com/gtfs/anaheim-ca-us/anaheim-ca-us.zip

Location: Anaheim Resort Area, California, United States

Data terms & guidelines are at: http://rideart.org/gtfs/

**Comment by HendX** [comment]
This has now been added: http://transitfeeds.com/p/anaheim-resort-transportation
