### ISSUE TITLE
Transit info for Sitka, Alaska

### ISSUE THREAD

**Issue by joshuahouston** [TransitFeeds/TransitFeeds-Public#170]
Agency: The RIDE
Sitka, Alaska  USA
[http://jfact0ry.com/theRIDE/transit_feed.zip](http://jfact0ry.com/theRIDE/transit_feed.zip)

**Comment by mldickens** [comment]
Is this an official feed? Looks like this is hosted on your personal blog.

**Comment by joshuahouston** [comment]
It is official and yes, it's my blog. The agency is a non-profit and only
has a wordpress.com site, which I could not use to host the feed.
http://ridesitka.com

**Comment by mldickens** [comment]
OK, I've added it http://transitfeeds.com/p/ride-sitka/713

**Comment by HendX** [comment]
Thanks @mldickens and @joshuahouston!
