### ISSUE TITLE
Add Israel GTFS data

### ISSUE THREAD

**Issue by AdiSegev** [TransitFeeds/TransitFeeds-Public#171]
Hi,

Can you add Israel GTFS data.

It can be downloaded from here: ftp://gtfs.mot.gov.il/.

GTFS data is at zip file named: israel-public-transportation.zip

Thank's

**Comment by HendX** [comment]
I've tried importing this into TransitFeeds but I'm having some trouble with it. I haven't figured out why - whether it's the RTL language, or the sheer size of the feed.

Will leave this open for now until a solution is found.

**Comment by joriswu** [comment]
I have processed it with my tools successfully.

**Comment by HendX** [comment]
I've got this importing now. https://transitfeeds.com/p/ministry-of-transport-and-road-safety/820
