### ISSUE TITLE
Byron Easybus

### ISSUE THREAD

**Issue by NeilSelkirk** [TransitFeeds/TransitFeeds-Public#173]
Hello,

Can you please add the feed for Byron Easybus?

Here's the link:
https://addtransit.com/gtfsfile/54743/ByronEasybus.zip

Byron's website is: https://www.byronbayshuttle.com.au/

Thanks,

Neil

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/byron-easybus/737

Sorry for the delay!
