### ISSUE TITLE
Add Bogor angkots

### ISSUE THREAD

**Issue by michielbdejong** [TransitFeeds/TransitFeeds-Public#174]
Bogor is a city in Indonesia with many minibuses ("angkots"), of which no map exists. I created a gtfs feed for them, see [repository](https://github.com/michielbdejong/bogor-angkot-gtfs) and [the zipfile](https://github.com/michielbdejong/bogor-angkot-gtfs/blob/master/release.zip?raw=true) (validated with AddTransit.com)

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/bogor-angkots
