### ISSUE TITLE
Dallas DART isn't importing the newest GTFS

### ISSUE THREAD

**Issue by colinmcglynn** [TransitFeeds/TransitFeeds-Public#175]
For some reason, the DART page isn't showing the newest GTFS even though the Official Download URL is right
https://transitfeeds.com/p/dart/26
http://www.dart.org/transitdata/latest/

**Comment by mldickens** [comment]
Looks like it updated on the 12th. The file may have been updated right after the script checked for a new version on the 11th.

**Comment by HendX** [comment]
I'm closing this for now since it appears to be resolved. If not please update here accordingly.
