### ISSUE TITLE
Errors and Warnings 

### ISSUE THREAD

**Issue by D-D-D-D** [TransitFeeds/TransitFeeds-Public#176]
Hi, 

It would be great if the API for getting feeds also included a validation report of some kind. Or, some sort of indication if the feed is usable or not. 

Thanks

**Comment by HendX** [comment]
Thanks for the request. The system doesn't make a determination at this time as to whether a feed is usable or not. I'm wondering though if there are some other validations each feed could be run against.

Could then return the errors and warnings with a corresponding "error ID" or something along those lines, so you can then make your own determination as to whether it's usable or not.

The errors and warnings system was mainly there to highlight potential issues you may face, but I still recommend you having your own validation and deciding whether or not to use a feed version. Note that each feed instance in the system has its own ID, so you can decide a particular version is no good and still be able to easily determine when that particular feed is updated so you can check again.

**Comment by HendX** [comment]
The `getFeedVersions` call now accepts two new parameters:

* `err=1` will enable output of errors
* `warn=1` will enable output of warnings.

Please post on here if there are any issues.

**Comment by D-D-D-D** [comment]
Thanks so much.
