### ISSUE TITLE
Feature Request: Filter 'getfeeds' by feed type

### ISSUE THREAD

**Issue by mldickens** [TransitFeeds/TransitFeeds-Public#178]
Would it be possible to add an input to the 'getfeeds' call so that we can filter the feeds by type? Right now there is no way to tell what is a GTFS feed, or a realtime feed, etc. and no way to get a list of just one type.

**Comment by HendX** [comment]
I've just added this functionality to the production site.

Firstly, `getfeeds` has a new optional parameter called `type` which accepts either:

* `gtfs`
* `gtfsrealtime`

This will filter the results accordingly.

Additionally, the feed data in the response now includes a `ty` parameter, which includes the type of the feed. Any value returned here is will valid the request `type` parameter (currently only the above two).

This is also mentioned on the API summary page.
