### ISSUE TITLE
Add data for VRS in Germany

### ISSUE THREAD

**Issue by HendX** [TransitFeeds/TransitFeeds-Public#179]
https://www.vrsinfo.de/fahrplan/oepnv-daten-fuer-webentwickler.html

Requested by @orless on Twitter.

**Comment by ubahnverleih** [comment]
Is now public available:
https://www.vrsinfo.de/fahrplan/oepnv-daten-fuer-webentwickler.html

with local trains: http://download.vrsinfo.de/gtfs/google_transit_DB.zip
without local trains: http://download.vrsinfo.de/gtfs/google_transit.zip

**Comment by benjaminburzan** [comment]
Hey @HendX will this API be added to TransitFeeds?
Thanks!

**Comment by HendX** [comment]
Added here: http://transitfeeds.com/p/verkehrsverbund-rhein-sieg/835

Thanks!
