### ISSUE TITLE
GTFS Trenord

### ISSUE THREAD

**Issue by stebazzi** [TransitFeeds/TransitFeeds-Public#182]
Please add Railway service in Lombardia, northern Italy

Many thanks

https://www.dati.lombardia.it/download/3z4k-mxz9/application%2Fzip

**Comment by HendX** [comment]
Thanks @stebazzi, I've added it here:

https://transitfeeds.com/p/trenord/724

Note that I've also reorganised the locations within Italy now, so it's split up by Region at the top level.

**Comment by stebazzi** [comment]
Great Job, many thanks
