### ISSUE TITLE
Niagara Region GTFS

### ISSUE THREAD

**Issue by danmackay** [TransitFeeds/TransitFeeds-Public#183]
http://maps-dev.niagararegion.ca/GoogleTransit/NiagaraRegionTransit.zip
https://niagaraopendata.ca/pages/open-government-license-2-0-niagara-region

covers all transit providers in niagara region, st catherines, welland, niagara falls, so on

**Comment by HendX** [comment]
Thanks @danmackay, added here: https://transitfeeds.com/p/regional-municipality-of-niagara/741
