### ISSUE TITLE
Warsaw GTFS Files

### ISSUE THREAD

**Issue by Natsuyasumi** [TransitFeeds/TransitFeeds-Public#185]
I'm providing a set of GTFS feeds for Warsaw, and, if possible, this feeds could be imported to your list:

Metro Warszawskie (Warsaw Metro) - http://otp-pl.tk/feed/MetroWaw/metrowaw-lastest.zip
ZTM Warszawa (Public Transport Authority of Warsaw) - http://otp-pl.tk/feed/ztm/ztm-latest.zip
Komunikacja Miejska Łomianki (Łomianki City Transportation) - http://otp-pl.tk/feed/kml/kml-latest.zip
Warszawska Kolej Dojazdowa (Warsaw Communter Railway) - http://otp-pl.tk/feed/wkd/wkd-latest.zip

**Comment by patrickbr** [comment]
I am getting a 404 for the metro feed, maybe the typo (`lastest` vs `latest`) is the reason? Getting a 404 for `metrowaw-latest.zip` too, though.

**Comment by Natsuyasumi** [comment]
I apologise for the confusion, I just moved feed location and pasted the old one. The new one is: http://otp-pl.tk/feed/metro/metro-latest.zip

**Comment by patrickbr** [comment]
Thanks, looks great! However, the metro feed contains some strange trips that only take 2-4 seconds between stations. Looks like the arrival and departure times have been "right-shifted" accidentally.

Example:

```
2sbr,0:00:00,0:00:00,dwi,1
2sbr,0:00:02,0:00:02,sta,2
2sbr,0:00:04,0:00:04,cnk,3
2sbr,0:00:06,0:00:06,nsu,4
2sbr,0:00:07,0:00:07,sw2,5
2sbr,0:00:09,0:00:09,ron,6
2sbr,0:00:11,0:00:11,rda,7
```

**Comment by Natsuyasumi** [comment]
Of course they were right-shifted, thanks for spotting that! I've updated the file, it should be ok now.

**Comment by patrickbr** [comment]
Thanks again :) I found one last issue with the KML feed, there is a line in stop_times.txt for a frequency-based trip where the arrival time is later than the depature time:

```
trip_id,arrival_time,departure_time,stop_id,stop_sequence
0f12d807-ad4c-4e52-992d-5bc7b09b20a5,06:25:00,00:00:00,STOP_c23401cf-62ac-4c29-a8e3-533db59b2adb,1,,0,0,0.0000000,0
```

**Comment by Natsuyasumi** [comment]
Ok, so I've fixed the KMŁ feed, the validator show no errors or warnings.

The WKD feeds produce these warnings:
- Feed will expire soon -> I'll update the feed soon
- route_short_name is long -> Intentional
- Overlapping Trips In Same Block -> Probably nothing I can do

As for the ZTM feed - the gtfs is created automatically from a ZTM file, so there's nothing to do unless ZTM fixes the mistake in their feed

**Comment by patrickbr** [comment]
Again, thank you very much. Great work. I can't speak for the TransitFeeds team whether they will include your feeds, but I have added them to TRAVIC (see [here](http://tracker.geops.de/?z=13&s=1&x=2339060.2826&y=6843154.5514&l=transport)).

**Comment by HendX** [comment]
Thanks! Added here:

http://transitfeeds.com/l/518-warsaw-poland
