### ISSUE TITLE
Valencia GTFS files

### ISSUE THREAD

**Issue by cprecioso** [TransitFeeds/TransitFeeds-Public#188]
Hi! I'd like to suggest the Valencia, Spain GTFS data. It's available at http://gobiernoabierto.valencia.es/en/resource/?ds=google-transit-lineas-paradas-horarios-de-autobuses&id=fff9be2c-090d-4008-8ef0-89e8fa41d05a

**Comment by cprecioso** [comment]
Direct link to the feed: https://opendata.vlci.valencia.es:8443/dataset/4645f8bf-28d7-4420-bab2-d5c5e7de2a5a/resource/11591648-a984-4d64-89e3-3730f3123403/download/googletransit.zip

**Comment by HendX** [comment]
Thanks @cprecioso, it's added here:

https://transitfeeds.com/p/emt-valencia
