### ISSUE TITLE
Revise interpolation rules for stop times without explicit arrival and departure times

### ISSUE THREAD

**Issue by nselikoff** [TransitFeeds/TransitFeeds-Public#191]
Thank you for creating and maintaining this GTFS clearinghouse!

Looking at the detail view for an example bus route for LYNX in Orlando, Florida: http://transitfeeds.com/p/central-florida-regional-transportation-authority/373/latest/trip/1176472

And the raw data from stop_times.txt: http://transitfeeds.com/p/central-florida-regional-transportation-authority/373/latest/file/stop_times.txt

You'll see that there are currently stop times that don't have explicit arrival and departure times. This is ok according to spec, and there is discretion on the GTFS consumer's side as to how to (or whether to) interpolate these times. In TransitFeeds however, the start time for the whole trip is being used for any stops that lack explicit arrival/departure times. So on the detail view, the schedule jumps back in time, which doesn't make sense.

One possibility is to use the most recent stop with explicit times. Another possibility is to indicate that the arrival and departure times are not specified for those stops with some other nomenclature, **\* for example.

**Comment by HendX** [comment]
Thanks for pointing this out @nselikoff - this is how it used to work, but a bug caused it to just default to the first found time for the trip.

Anyway, it's fixed now!

**Comment by nselikoff** [comment]
Awesome, thanks @HendX!
