### ISSUE TITLE
Provider suggestion: Gold Country Stage, Nevada County California

### ISSUE THREAD

**Issue by alexfriant** [TransitFeeds/TransitFeeds-Public#192]
Here's the GTFS.zip link for Gold County Stage in Nevada County, California:
[http://gis.nevcounty.net/GTFS/GTFS.zip](http://gis.nevcounty.net/GTFS/GTFS.zip)

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/gold-country-stage/749
