### ISSUE TITLE
Poland > Lublin

### ISSUE THREAD

**Issue by Natsuyasumi** [TransitFeeds/TransitFeeds-Public#200]
I found a GTFS feed of a agency "ZTM Lublin", operating in Lublin: http://iplaner.pl/cvs2gtfs/lublin/GTFS_lublin/GTFS_lublin.zip

**Comment by HendX** [comment]
Hi @Natsuyasumi, I just checked but that's a 404 now

**Comment by Natsuyasumi** [comment]
It seems like [their whole website](http://iplaner.pl/lublin) got shut down. I can't find any information about this situation.

**Comment by stevevance** [comment]
I'm looking for the replacement URL, also.

**Comment by Natsuyasumi** [comment]
Some time has passed and this feed is still not available.
