### ISSUE TITLE
Thailand > Chiang Mai

### ISSUE THREAD

**Issue by TumThings** [TransitFeeds/TransitFeeds-Public#203]
Here are the feed for Chiang Mai City & Near by Provinces, Thailand.

GreenBusThailand		http://119.59.103.163/CM/GreenBus/greenbus_transit.zip
KwanWiang			http://119.59.103.163/CM/KwanWiang/kwanwiang_transit.zip
WhiteBus			http://119.59.103.163/CM/WhiteBus/whitebus_transit.zip
South_Route			http://119.59.103.163/CM/South/south_route.zip

East & Northern Routes will be submitted later.

Anucha Promwungkwa,
anucha@eng.cmu.ac.th

**Comment by fede843** [comment]
Green bus covers in fact most of country, isn't it?

**Comment by TumThings** [comment]
Dear Federico,

The Greenbus service is mainly covered the Northern provinces of Thailand.
However, it also covers some part of the country like the Southern and
North-East provinces.

There are another bus-agency mainly cover each part of the country.  I am
planning to get support from Thai government to train people to create
public GTFS for all routes.

Hope this make you clear.

Regards,
Anucha Promwungkwa

**Comment by fede843** [comment]
Very clear. 
Thanks Anucha.

**Comment by HendX** [comment]
- [ ] GreenBusThailand
- [ ] KwanWian
- [ ] WhiteBus
- [ ] South_Route

**Comment by promwungkwa** [comment]
New feed from Chiang Mai, Thailand.  It's a transportation in Chiang Mai University.

http://www.thaitransit.org/CM/CMU/cmu_transit.zip

**Comment by HendX** [comment]
Thanks @promwungkwa, it has been added here: https://transitfeeds.com/p/chiang-mai-university/788

**Comment by promwungkwa** [comment]
The last set of new GTFS feeds for Chiang Mai, Thailand.  Together with the previous feeds, those will cover 80% of mini-bus and bus feeds in the province.

South Route 2: 		http://www.thaitransit.org/CM/South/south_route2.zip
North				http://www.thaitransit.org/CM/North/north_route.zip
West				http://www.thaitransit.org/CM/West/west_route.zip
East					http://www.thaitransit.org/CM/East/east_route.zip

Best Regards,
Anucha Promwungkwa

**Comment by joriswu** [comment]
The first set of feeds at http://119.59.103.163 are no longer accessible. I tried http://www.thaitransit.org/CM/GreenBus/greenbus_transit.zip instead, but also not present.

**Comment by promwungkwa** [comment]
Dear Wu,

Sorry for my mistake. I have put back http://www.thaitransit.org/CM/
GreenBus/greenbus_transit.zip into the server.

Regards,
Anucha Promwungkwa

**Comment by HendX** [comment]
These have been added, and the previous URLs updated.
