### ISSUE TITLE
Poland > Warsaw

### ISSUE THREAD

**Issue by Natsuyasumi** [TransitFeeds/TransitFeeds-Public#206]
I have created new feeds for Warsaw railway providers:

Koleje Mazowieckie - [http://otp-pl.tk/feed/kmaz/kmaz-latest.zip](http://otp-pl.tk/feed/kmaz/kmaz-latest.zip)
Szybka Kolej Miejska w Warszawie - [http://otp-pl.tk/feed/kmaz/kmaz-latest.zip](http://otp-pl.tk/feed/kmaz/kmaz-latest.zip)

**Comment by HendX** [comment]
Thanks - I've added these.

Btw, I think you meant http://otp-pl.tk/feed/skm/skm-latest.zip for the 2nd link, so I used that one.
