### ISSUE TITLE
Norway

### ISSUE THREAD

**Issue by gtfs0** [TransitFeeds/TransitFeeds-Public#208]
There is a gtfs feed for Norway here:
https://data.norge.no/data/norsk-reiseinformasjon/nasjonale-rutedata-norge
Just download directly, no registration needed.
It would be nice to have it at TransitFeeds.

**Comment by HendX** [comment]
Thanks, I've added it here:

https://transitfeeds.com/p/norsk-reiseinformasjon-as/791
