### ISSUE TITLE
NICEBus Update

### ISSUE THREAD

**Issue by stripolias** [TransitFeeds/TransitFeeds-Public#209]
Hey guys!

There is a new GTFS for NICEBus (Nassau,NY) file here:
http://www.nicebus.com/NiceBus/media/Nicebus-FrontPageNewsImages/NICE_GTFS_117.zip 

To be updated in:
https://transitfeeds.com/p/nassau-inter-county-express/268

**Comment by HendX** [comment]
Thanks - updated
