### ISSUE TITLE
Louisville, KY GTFS-RT feed location

### ISSUE THREAD

**Issue by schnuerle** [TransitFeeds/TransitFeeds-Public#21]
Louisville also has RT data for about a year now. 
http://transitfeeds.com/l/199-louisville-ky-usa
http://transitfeeds.com/p/transit-authority-of-river-city

You have the GTFS feed already:
http://transitfeeds.com/p/transit-authority-of-river-city/265

Here is the GTFS-RT feed:
http://gtfsrealtime.ridetarc.org/

Thanks!

**Comment by HendX** [comment]
Thanks Michael - I've just added them here:

http://transitfeeds.com/p/transit-authority-of-river-city
