### ISSUE TITLE
JTA GTFS URL changed

### ISSUE THREAD

**Issue by barbeau** [TransitFeeds/TransitFeeds-Public#211]
For JTA:
http://transitfeeds.com/p/jacksonville-transportation-authority/331

New GTFS URL is:
http://www.jtafla.com/umbraco/surface/schedulesgtfs/index

**Comment by HendX** [comment]
Hi @barbeau - this gives a 404. I couldn't find any GTFS on their site through the main nav / search.

**Comment by barbeau** [comment]
Hmmm, let me check with JTA again. Looks like they moved something.

**Comment by barbeau** [comment]
Ok, looks like it's moved to:
https://schedules.jtafla.com/schedulesgtfs/download

For future reference, the page that lists the link is at:
http://www.jtafla.com/schedules/

**Comment by HendX** [comment]
Thanks @barbeau, fixed here: https://transitfeeds.com/p/jacksonville-transportation-authority/331

**Comment by barbeau** [comment]
Thanks!
