### ISSUE TITLE
/getFeedVersion - no response from server

### ISSUE THREAD

**Issue by SymbolixAU** [TransitFeeds/TransitFeeds-Public#212]
I'm receiving the 

```
{
  "error": "no response from server"
}
```
For both `/getLatestFeedVersion` and `/getFeedVersion`. Are you able to confirm if this this a server error or something I should look into at my end? 

`/getFeeds` and `/getLocations` work as expected

**Comment by HendX** [comment]
Hi @SymbolixAU - I just checked and they worked for me.

I think Swagger-UI can be a bit misleading with the responses sometimes. Can you try pasting the URL generated on that interface directly into your browser to see the error?

It's likely either an invalid API key, or an invalid feed ID.

If those are correct, please include the URL here (please omit your API key though) and I'll investigate further.

**Comment by SymbolixAU** [comment]
This is the url for `/getFeedVersions`

```
https://api.transitfeeds.com/v1/getFeedVersions?key=my_key_goes_here&feed=undefined&page=1&limit=10&err=1&warn=1
```

And this is is the result when used in Chrome

```
{"status":"INVALIDINPUT","ts":1485211182,"results":{"input":"feed"}}
```

so looks like a `ts` issue?

It's my understanding the `/getFeedVersions` only requires the KEY field, the others are optional?

**Comment by HendX** [comment]
Try removing `feed=undefined` from the URL (or set the value to blank). It's a bug with Swagger-UI that pre-populates this. I need to update it so it no longer does that.

**Comment by SymbolixAU** [comment]
Yep, that seems to have done the trick!

Thanks very much
