### ISSUE TITLE
FR - Royan

### ISSUE THREAD

**Issue by MilleMiles** [TransitFeeds/TransitFeeds-Public#213]
Hi,
You can add Royan (FR), Cara'bus network: https://data.agglo-royan.fr/dataset/donnees-gtfs-du-reseau-de-transport-public-cara-bus
Thx!

**Comment by HendX** [comment]
This URL doesn't appear to update automatically when there's new data. Do you know of a permalink?

**Comment by MilleMiles** [comment]
Permalink here: [https://www.data.gouv.fr/fr/datasets/donnees-gtfs-du-reseau-de-transport-public-carabus/](url)

**Comment by HendX** [comment]
I'm sorry but I don't see a direct download link to the GTFS data, only individual files

**Comment by stevevance** [comment]
Here's the ZIP file: https://navitia.opendatasoft.com/explore/dataset/fr-sw/files/abb6edb6b32223b7c5c1e55b37563d6f/download/

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/carabus/873
