### ISSUE TITLE
Transit feeds for Queensland

### ISSUE THREAD

**Issue by SymbolixAU** [TransitFeeds/TransitFeeds-Public#216]
Hi,

It appears your feeds for regional Queensland (i.e., not Brisbane) are out of date. I know that data.qld did a lot of updates to their data/API recently; are you still pointing to the correct source:

https://data.qld.gov.au/dataset/general-transit-feed-specification-gtfs-qconnect

Cheers,

**Comment by HendX** [comment]
Thanks @SymbolixAU, I've updated all of the links.
