### ISSUE TITLE
New GTFS Feed - The Victoria Clipper

### ISSUE THREAD

**Issue by NeilSelkirk** [TransitFeeds/TransitFeeds-Public#217]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: United Status______________________

- [ ] REGION: Washington______________________

- [ ] CITY: Seattle______________________

- [ ] DIRECT DOWNLOAD URL: https://addtransit.com/gtfsfile/42017/TheVictoriaClipper.zip
  This is the URL of the GTFS zip
  
- [ ] FEED ACCESS INFO:  N/A
  This is a web page with more information about the feed (such as licensing or access instructions)

- [ ] This feed is reliably updated: Yes

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions) : Yes

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/the-victoria-clipper/800
