### ISSUE TITLE
GTFS for Praha (Czech Republic)

### ISSUE THREAD

**Issue by mkosmach** [TransitFeeds/TransitFeeds-Public#218]
- [*] COUNTRY:  Czech Republic (Česká republika)

- [ ] REGION: 

- [*] CITY: Praha

- [*] DIRECT DOWNLOAD URL: http://opendata.iprpraha.cz/DPP/JR/jrdata.zip

- [*] FEED ACCESS INFO: http://opendata.praha.eu/dataset/dpp-jizdni-rady

- [*] This feed is reliably updated

- [*] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/praha/801
