### ISSUE TITLE
Add GTFS for Votran (Daytona Beach area - Florida - USA)

### ISSUE THREAD

**Issue by wideanglefocus** [TransitFeeds/TransitFeeds-Public#219]
COUNTRY: United States of America
REGION:     Southeast - State of Florida
CITY:          Daytona Beach area

DIRECT DOWNLOAD URL: http://www.votran.org/core/fileparse.php/6120/urlt/google_transit_3.zip

FEED ACCESS INFO: http://www.votran.org/about-us/data.stml

This feed is reliably updated.

This is an official feed.

**Comment by HendX** [comment]
Thank @wideanglefocus - GTFS and GTFS-realtime feeds have been added here: http://transitfeeds.com/p/votran
