### ISSUE TITLE
Add GTFS-realtime for Votran (Daytona Beach area - Florida - USA)

### ISSUE THREAD

**Issue by wideanglefocus** [TransitFeeds/TransitFeeds-Public#220]
COUNTRY: United States of America
REGION: Southeast - State of Florida
CITY: Daytona Beach area

VoTran uses a proprietary real-time tracking service currently operated by Availtec.  My partner Nathan Selikoff and I met with Availtec & Votran teams to request GTFS-realtime feeds, which they provided but have not published online (Nathan and I have a company called Omni specializing in GTFS).

Proprietary REST API:
http://realtimevotran.availtec.com/InfoPoint/swagger/ui/index

GTFS-realtime feeds: 

Vehicle Positions:  http://realtimevotran.availtec.com/infopoint/GTFS-Realtime.ashx?&Type=VehiclePosition&debug=true

Trip Updates:  http://realtimevotran.availtec.com/infopoint/GTFS-Realtime.ashx?&Type=TripUpdate&debug=true

Note, included “&debug=true” to see the feed; exclude it to see the protobuf

FEED ACCESS INFO: http://www.votran.org/about-us/data.stml (website not updated yet with GTFS-realtime feed links - pending)

This feed is reliably updated.

This is an official feed.

**Comment by HendX** [comment]
Thank @wideanglefocus - GTFS and GTFS-realtime feeds have been added here: http://transitfeeds.com/p/votran
