### ISSUE TITLE
Poland > Warsaw - Update

### ISSUE THREAD

**Issue by MKuranowski** [TransitFeeds/TransitFeeds-Public#224]
I have changed a bit the specifiaction of Warsaw's feeds:

Metro Warszawskie and Szybka Kolej Miejska w Warszawie schedules are now included in ZTM Warszawa feed.

Also, new Koleje Mazowieckie schedules don't allow for GTFS creation, therefore I had to put their feed down. As a temporary solution I will include purned Koleje Mazowieckie, from ZTM's feed, in the ZTM Warszawa GTFS.

Additionaly, I have created GTFS-Realtime Alerts feed for ZTM Warszawa - available at [http://otp-pl.tk/feed/ztm/ztm-alerts.pb](http://otp-pl.tk/feed/ztm/ztm-alerts.pb)

**Comment by Natsuyasumi** [comment]
And, I have also created a GTFS-RT Vehicle Positions feed, at http://otp-pl.tk/feed/ztm/ztm-vehicles.pb - but using it requires a credit to "Miasto Stoleczne Warszawa" alongside with the date when this feed was downloaded.

**Comment by MKuranowski** [comment]
Since this issue is still open:

I have switched domains and added the HTTPS protocol - the feeds' download URL will now start from [https://mkuran.pl/](https://mkuran.pl/).

The new feeds' locations are:
- ZTM Warszawa: [https://mkuran.pl/feed/ztm/ztm-latest.zip](https://mkuran.pl/feed/ztm/ztm-latest.zip)
- Warszawska Kolej Dojazdowa: [https://mkuran.pl/feed/wkd/wkd-latest.zip](https://mkuran.pl/feed/wkd/wkd-latest.zip)
- Komunikacja Miejska Łomianki: [https://mkuran.pl/feed/kml/kml-latest.zip](https://mkuran.pl/feed/kml/kml-latest.zip).

**Comment by HendX** [comment]
Thanks, updated.
