### ISSUE TITLE
California - Caltrain updated the location of their GTFS file

### ISSUE THREAD

**Issue by 3vivekb** [TransitFeeds/TransitFeeds-Public#225]
Region:
North America US CA San Francisco Caltrain Caltrain GTFS

This is the URL of the GTFS zip
http://www.caltrain.com/Assets/GTFS/caltrain/CT-GTFS.zip
(The old location was http://www.caltrain.com/Assets/GTFS/caltrain/Caltrain-GTFS.zip)

- [ ] This feed is reliably updated
Not sure

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks @3vivekb - updated.
