### ISSUE TITLE
Halifax, NS Realtime-GTFS

### ISSUE THREAD

**Issue by asherism** [TransitFeeds/TransitFeeds-Public#226]
Halifax, Nova Scotia, Canada

[Download page for protocol buffer files](http://www.halifax.ca/opendata/transit.php)
[Licence agreement](http://www.halifax.ca/opendata/OD_TermsOfUse.php)

✅ This feed is reliably updated
✅ This is an official feed

**Comment by HendX** [comment]
Thanks @asherism - added here: https://transitfeeds.com/p/metrotransit
