### ISSUE TITLE
Berlin GTFS feed link is incorrect

### ISSUE THREAD

**Issue by digital2000** [TransitFeeds/TransitFeeds-Public#228]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x ] COUNTRY: _Germany_____________________

- [x ] REGION: _______Europe_______________

- [x] CITY: _________Berlin_____________

- [x ] DIRECT DOWNLOAD URL: http://www.vbb.de/de/datei/GTFS.zip
  This is the URL of the GTFS zip
  
- [ ] FEED ACCESS INFO: https://
  This is a web page with more information about the feed (such as licensing or access instructions)

- [ ] This feed is reliably updated

- [x ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks @digital2000, updated.
