### ISSUE TITLE
Hungary > Pécs

### ISSUE THREAD

**Issue by enmyx** [TransitFeeds/TransitFeeds-Public#229]
Could you add GTFS feed of Pécs, Hungary?
Thanks.

- [X] COUNTRY: Hungary

- [ ] REGION: 

- [X] CITY: Pécs

- [X] DIRECT DOWNLOAD URL: http://mobilitas.biokom.hu/gtfs
  This is the URL of the GTFS zip
  
- [X] FEED ACCESS INFO: http://mobilitas.biokom.hu/en/google#developers
  This is a web page with more information about the feed (such as licensing or access instructions)

- [X] This feed is reliably updated

- [X] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks, added here: http://transitfeeds.com/p/biokom-nonprofit/838
