### ISSUE TITLE
New official feed link for Thunder Bay Transit

### ISSUE THREAD

**Issue by jhendel** [TransitFeeds/TransitFeeds-Public#23]
Thunder Bay Transit has new official links to GTFS data:

GTFS:
http://api.nextlift.ca/gtfs.zip

GTFS-realtime:
http://api.nextlift.ca/gtfs-realtime/vehicleupdates.pb 
http://api.nextlift.ca/gtfs-realtime/tripupdates.pb 
http://api.nextlift.ca/gtfs-realtime/alerts.pb

**Comment by HendX** [comment]
Thanks! The GTFS URL has been updated and the GTFS-realtime feeds have been added here:

http://transitfeeds.com/p/thunder-bay-transit
