### ISSUE TITLE
Hungary > Miskolc

### ISSUE THREAD

**Issue by enmyx** [TransitFeeds/TransitFeeds-Public#230]
Could you add GTFS feed of Miskolc, Hungary?
Thanks.

- [X] COUNTRY: Hungary

- [x] REGION: 

- [X] CITY: Miskolc

- [X] DIRECT DOWNLOAD URL: http://siri.ktikmk.hu/gtfs-static/mvkzrt.zip
  This is the URL of the GTFS zip
  
- [X] FEED ACCESS INFO: http://www.mvkzrt.hu/menetrend
  (There is no english version of this page. It's stated there they update the feed daily.)
  This is a web page with more information about the feed (such as licensing or access instructions)

- [X] This feed is reliably updated

- [X] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks, added here: http://transitfeeds.com/p/mvk-zrt/839
