### ISSUE TITLE
BART GTFS calendar issue

### ISSUE THREAD

**Issue by 3vivekb** [TransitFeeds/TransitFeeds-Public#232]
I'm looking at the BART GTFS.
(We are having some trouble with it - something must be wrong.)
http://transitfeeds.com/p/bart/58/latest

I am looking at the calendar.txt and comparing it to the header on your page.

The calendar.txt say it is valid for 
```
20170325,20180630
```

But your site says it is valid for 
![transitfeeds_snip](https://cloud.githubusercontent.com/assets/4524205/24014371/eee58c06-0a41-11e7-8b26-c89149398638.PNG)

This feed is currently in service! 
(5 September 2016 - 30 June 2018)

Thoughts?

**Comment by HendX** [comment]
This because of an entry in `calendar_dates.txt` that is 5 Sept 16:

http://transitfeeds.com/p/bart/58/latest/file/calendar_dates.txt
