### ISSUE TITLE
CARTA GTFS

### ISSUE THREAD

**Issue by mldickens** [TransitFeeds/TransitFeeds-Public#234]
https://transitfeeds.com/p/chattanooga-area-regional-transportation-authority/360

The link looks right to me and downloads when I use it, but the system is unable to download the file - we get an HTTP 400 error.

**Comment by HendX** [comment]
Fixed - it turns out this site doesn't like it when there's no User-Agent header specified. All TransitFeeds requests should now include this - hopefully it doesn't impact other sites.
