### ISSUE TITLE
Please add GTFS feed for Praha, Czech Republic

### ISSUE THREAD

**Issue by mkosmach** [TransitFeeds/TransitFeeds-Public#235]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [v] COUNTRY: Czech Republic

- [v] REGION: 

- [v] CITY: Praha

- [v] DIRECT DOWNLOAD URL: http://opendata.iprpraha.cz/DPP/JR/jrdata.zip
  This is the URL of the GTFS zip
  
- [v] FEED ACCESS INFO: http://opendata.praha.eu/dataset/dpp-jizdni-rady/resource/5d122701-b081-44c3-91be-060a30d09b6a
  This is a web page with more information about the feed (such as licensing or access instructions)

- [v] This feed is reliably updated

- [v] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks @mkosmach - is this different to the following feed? https://transitfeeds.com/p/praha/801

**Comment by Manu1400** [comment]
the feed access info updated :
* [x] FEED ACCESS INFO: http://opendata.praha.eu/dataset/dpp-jizdni-rady

**Comment by HendX** [comment]
Thanks - already had this one in the system.
