### ISSUE TITLE
City Request: London Ontario

### ISSUE THREAD

**Issue by Denholm** [TransitFeeds/TransitFeeds-Public#236]
Feed request for London Transit Commission. 

Canada 
London, Ontario
London Transit Commission

Direct download: http://www.ltconline.ca/gtfsfeed/google_transit.zip
Licensing info: https://www.london.ca/city-hall/open-data/Pages/OpenData-TermsofUse.aspx

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/london-transit-commission/831
