### ISSUE TITLE
City Request: Regina Saskatchewan

### ISSUE THREAD

**Issue by Denholm** [TransitFeeds/TransitFeeds-Public#237]
Feed request for Regina SK, Canada

Canada
Regina, Saskatchewan 
The City of Regina

Direct Download: https://opengis.regina.ca/reginagtfs/google_transit.zip
Licensing info: http://open.regina.ca/dataset/transit-network

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/the-city-of-regina/830
