### ISSUE TITLE
City Request: Moncton, New Brunswick

### ISSUE THREAD

**Issue by Denholm** [TransitFeeds/TransitFeeds-Public#238]
Feed request for Moncton, New Brunswick

Canada
Moncton, New Brunswick
City of Moncton Codiac Transpo Division

Direct download: http://www.moncton.ca/gtfs/google_transit.zip
Licensing info: http://www.moncton.ca/Government/Terms_of_use/Open_Data_Purpose/Data_Catalogue/Transit_Files__GTFS_.htm

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/codiac-transpo/829
