### ISSUE TITLE
 City Request:  Gatineau, Quebec 

### ISSUE THREAD

**Issue by Denholm** [TransitFeeds/TransitFeeds-Public#239]
Feed request for Gatineau, Quebec 

Canada
Gatineau, Quebec 
Société de transport de l'Outaouais' (STO)

Direct Download: http://www.contenu.sto.ca/GTFS/GTFS.zip
Licensing info: http://www.sto.ca/index.php?id=596&L=en

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/societe-de-transport-de-loutaouais/828
