### ISSUE TITLE
Feed Request: http://www.oregon-gtfs.com/

### ISSUE THREAD

**Issue by invisiblefunnel** [TransitFeeds/TransitFeeds-Public#24]
Nice to meet you @HendX! I'm following up from our [Twitter conversation](https://twitter.com/transitmixapp/status/573968573485334528).

www.oregon-gtfs.com seems to be the most complete repository of GTFS for the state of Oregon. Some feeds are already covered: http://transitfeeds.com/l/63-oregon-usa. We're interested in bringing the remaining feeds onboard. How can we (Transitmix) help?

**Comment by HendX** [comment]
Thanks - I've actually got a (csv) list of a bunch of feeds I need to add currently, including all the Oregon ones that currently aren't there. I'm planning to knock this out in the next week or so.

Another todo that I have is to improve the admin section of the site to allow other collaborators so submit feeds. Currently it only allows me, so please bear with me while I get them added

**Comment by invisiblefunnel** [comment]
Sounds great! Thanks @HendX.

**Comment by HendX** [comment]
These are all added now. If you notice that I've missed one, please reopen this issue

**Comment by invisiblefunnel** [comment]
Thank you @HendX
