### ISSUE TITLE
City Request: Sherbrooke Quebec

### ISSUE THREAD

**Issue by Denholm** [TransitFeeds/TransitFeeds-Public#240]
Feed request for Sherbrooke QC, Canada

Canada
Sherbrooke, Quebec
Sherbrooke Transportation Company

Direct Download: https://www.donneesquebec.ca/recherche/dataset/e82b9141-09d8-4f85-af37-d84937bc2503/resource/b7f43b2a-2557-4e3b-ba12-5a5c6d4de5b1/download/gtfssherbrooke.zip

Licensing info: https://www.donneesquebec.ca/recherche/fr/dataset/transport-sts

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/societe-de-transport-de-sherbrooke/827
