### ISSUE TITLE
NMBS SNCB feed not getting updated

### ISSUE THREAD

**Issue by pc32** [TransitFeeds/TransitFeeds-Public#242]
According to http://transitfeeds.com/p/societe-nationale-des-chemins-de-fer-belges/528 the feed was updated in April 2016. 
Clearly this isn't the case. The feed at http://gtfs.irail.be/nmbs/nmbs-latest.zip has a timestamp later than that.

Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: _______Belgium_______________

- [ ] REGION: ______________________

- [ ] CITY: ______________________

- [ ] DIRECT DOWNLOAD URL: http://gtfs.irail.be/nmbs/nmbs-latest.zip
  This is the URL of the GTFS zip
  
- [ ] FEED ACCESS INFO: https://
  This is a web page with more information about the feed (such as licensing or access instructions)

- [x ] This feed is reliably updated

- [ x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Fixed.
