### ISSUE TITLE
De Lijn not getting updated

### ISSUE THREAD

**Issue by pc32** [TransitFeeds/TransitFeeds-Public#243]
The feed De Lijn isn't getting updated the way it should.

According to http://transitfeeds.com/p/vlaamse-vervoersmaatschappij-de-lijn/530 the feed was updated September 2016, however http://gtfs.irail.be/de-lijn/de_lijn-gtfs.zip is from April 2017.

Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: _________Belgium_____________

- [ ] REGION: ______________________

- [ ] CITY: ______________________

- [ ] DIRECT DOWNLOAD URL: http://gtfs.irail.be/de-lijn/de_lijn-gtfs.zip
  This is the URL of the GTFS zip
  
- [ ] FEED ACCESS INFO: https://
  This is a web page with more information about the feed (such as licensing or access instructions)

- [x ] This feed is reliably updated

- [ x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Like the other feed, this was the IPv6 issue. Fixed now.
