### ISSUE TITLE
Feed Tec is not getting updated.

### ISSUE THREAD

**Issue by pc32** [TransitFeeds/TransitFeeds-Public#244]
The feed TEC is not getting update the way it should.

According to http://transitfeeds.com/p/societe-regionale-wallonne-du-transport/529 the feed was updated in September 2016, however http://gtfs.irail.be/tec/tec-gtfs.zip is from April 2017.

Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: _________________Belgium_____

- [ ] REGION: ______________________

- [ ] CITY: ______________________

- [ ] DIRECT DOWNLOAD URL: http://gtfs.irail.be/tec/tec-gtfs.zip
  This is the URL of the GTFS zip
  
- [ ] FEED ACCESS INFO: https://
  This is a web page with more information about the feed (such as licensing or access instructions)

- [ x] This feed is reliably updated

- [x ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
It appears TransitFeeds was resolving to their IPv6 address, which caused an issue. Changed to force IPv4 now.
