### ISSUE TITLE
Feed STIB-MIVB not getting updated

### ISSUE THREAD

**Issue by pc32** [TransitFeeds/TransitFeeds-Public#245]
The feed STIB-MIVB is not getting updated the way it should. 

According to http://transitfeeds.com/p/societe-des-transports-intercommunaux-de-bruxelles/527 the feed was updated in January 2017, however http://gtfs.irail.be/mivb/mivb-gtfs.zip is from April 2017.

Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: ______Belgium________________

- [ ] REGION: ______________________

- [ ] CITY: ______________________

- [ ] DIRECT DOWNLOAD URL: http://gtfs.irail.be/mivb/mivb-gtfs.zip
  This is the URL of the GTFS zip
  
- [ ] FEED ACCESS INFO: https://
  This is a web page with more information about the feed (such as licensing or access instructions)

- [x ] This feed is reliably updated

- [x ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
I moved the feed to their official URL but I've had a lot of trouble automating the retrieval of this feed due to the way they do their authorisation. I'll switch it back to the URL you've included.
