### ISSUE TITLE
Belle Urban System in Racine, WI

### ISSUE THREAD

**Issue by christrillium** [TransitFeeds/TransitFeeds-Public#246]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: __________________USA____

- [ ] REGION: __Wisconsin____________________

- [ ] CITY: _____Racine_________________

- [ ] DIRECT DOWNLOAD URL: http://data.trilliumtransit.com/gtfs/racine-wi-us/racine-wi-us.zip
  

- [ X] This feed is reliably updated

- [ X] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks, added here: http://transitfeeds.com/p/city-of-racine/832
