### ISSUE TITLE
Cities Area Transit Feed

### ISSUE THREAD

**Issue by mldickens** [TransitFeeds/TransitFeeds-Public#247]
Trying to add the feed for Cities Area Transit (Grand Forks, ND):
https://transitfeeds.com/admin/feeds/feed.php?f=834

It's hosted on an FTP site but it looks like it's getting a "connection timed out" error. When I access the link from my browser it works just fine.

**Comment by HendX** [comment]
Fixed now. Believe it was an issue related to passive FTP transfer.
