### ISSUE TITLE
Download url changed for Tasmania, AU

### ISSUE THREAD

**Issue by ecarinae** [TransitFeeds/TransitFeeds-Public#248]
The official download URL for all the Tasmanian sites (Hobart, Launceston and Burnie) are returning 404 errors (e.g. `https://www.metrotas.com.au/transit/Hobart/google_transit.zip`)

It seems that the links have changed - I poked around the MetroTas website and it appears they all now link from `https://www.metrotas.com.au/community/gtfs/` instead.  The downloads from the new site (at least for Hobart) see up to date.

cheers

**Comment by HendX** [comment]
Thanks - updated
