### ISSUE TITLE
Add GTFS Feed for AVV (Germany)

### ISSUE THREAD

**Issue by benjaminburzan** [TransitFeeds/TransitFeeds-Public#250]
- [X] COUNTRY: GERMANY

- [X] REGION: Aachen

- [X] DIRECT DOWNLOAD URL: http://opendata.avv.de/current_GTFS/AVV_GTFS_mit_SPNV.zip
  
- [X] FEED ACCESS INFO: http://opendata.avv.de/

- [X] This feed is reliably updated

- [X] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by ubahnverleih** [comment]
Now also available on this official Page: http://opendata.avv.de/
maybe this link is more static: http://opendata.avv.de/current_GTFS/AVV_GTFS_mit_SPNV.zip

License: http://opendata.avv.de/current_GTFS/lizenz_und_readme.txt (public domain)

**Comment by benjaminburzan** [comment]
I updated my original post. Thanks @ubahnverleih!

**Comment by HendX** [comment]
Thanks, added here: http://transitfeeds.com/p/aachener-verkehrsverbund/836
