### ISSUE TITLE
Ferrotramviaria GTFS

### ISSUE THREAD

**Issue by managai** [TransitFeeds/TransitFeeds-Public#251]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [*] COUNTRY: ITALY

- [*] REGION: PUGLIA

- [*] CITY: BARI

- [*] DIRECT DOWNLOAD URL: http://www.ferrovienordbarese.it/download/?type=upload&id=786
  This is the URL of the GTFS zip
  
- [*] FEED ACCESS INFO: http://www.ferrovienordbarese.it/orari
  This is a web page with more information about the feed (such as licensing or access instructions)

- [*] This feed is reliably updated

- [*] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/ferrotramviaria-spa

**Comment by stebazzi** [comment]
Attention please.
Ferrotranviaria was added in January 2015. The link is http://transitfeeds.com/p/ferrotramviaria/412
So, this issue is a duplicate

Many thanks
