### ISSUE TITLE
Barrie Transit Url Changes+Additions

### ISSUE THREAD

**Issue by useless2764** [TransitFeeds/TransitFeeds-Public#252]
http://www.myridebarrie.ca/gtfs/Google_transit.zip

http://www.myridebarrie.ca/gtfs/GTFS_ServiceAlerts.pb
http://www.myridebarrie.ca/gtfs/GTFS_TripUpdates.pb
http://www.myridebarrie.ca/gtfs/GTFS_VehiclePositions.pb

**Comment by HendX** [comment]
Thanks, all updated / added: 
https://transitfeeds.com/admin/providers/provider.php?p=295
