### ISSUE TITLE
Norwalk Transit System addition to TransitFeeds

### ISSUE THREAD

**Issue by christrillium** [TransitFeeds/TransitFeeds-Public#253]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: ______US________________

- [ ] REGION: _______California_______________

- [ ] CITY: ______Norwalk________________

- [ ] DIRECT DOWNLOAD URL:
http://data.trilliumtransit.com/gtfs/nts-ca-us/nts-ca-us.zip  
- [ ] FEED ACCESS INFO:
  This is a web page with more information about the feed (such as licensing or access instructions)
N/A
- [ ] This feed is reliably updated---YES

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)
YES

**Comment by HendX** [comment]
Thanks @christrillium, added here: https://transitfeeds.com/p/norwalk-transit-system/846
