### ISSUE TITLE
Saskatoon Transit GTFS-Realtime Feeds

### ISSUE THREAD

**Issue by kencon** [TransitFeeds/TransitFeeds-Public#254]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: **Canada**

- [ ] REGION: **Alberta**

- [ ] CITY: **Saskatoon**

- [ ] DIRECT DOWNLOAD URL: https://
  **Vehicle Positions**: http://apps2.saskatoon.ca/app/data/Vehicle/VehiclePositions.pb
  **Trip Updates**: http://apps2.saskatoon.ca/app/data/TripUpdate/TripUpdates.pb
  **Alerts**: http://apps2.saskatoon.ca/app/data/Alert/Alerts.pb
  
- [ ] FEED ACCESS INFO: http://opendata-saskatoon.cloudapp.net/TermsOfUse/TermsOfUse

- [ ] This feed is reliably updated: **YES**

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions) **YES**

**Comment by HendX** [comment]
Thanks @kencon - added here: https://transitfeeds.com/p/city-of-saskatoon
