### ISSUE TITLE
FR - Add Metz

### ISSUE THREAD

**Issue by Manu1400** [TransitFeeds/TransitFeeds-Public#255]
- [x] COUNTRY: France (Europe)

- [x] REGION: Grand Est

- [x] CITY: Metz (Metz)

- [x] DIRECT DOWNLOAD URL: http://geo-ws.metzmetropole.fr/services/opendata/gtfs_current.zip or with HTTPS : https://geo-ws.metzmetropole.fr/services/opendata/gtfs_current.zip
  
- [x] FEED ACCESS INFO: http://www.data.gouv.fr/fr/datasets/transport-donnees-gtfs/

- [x] This feed is reliably updated

- [x] This is an official feed

**Comment by HendX** [comment]
Thanks @Manu1400, added here: https://transitfeeds.com/p/metz-metropole/850
