### ISSUE TITLE
MARTA Trip Updates Feed Info/Terms of Use link broken

### ISSUE THREAD

**Issue by akinhwan** [TransitFeeds/TransitFeeds-Public#256]
http://www.itsmarta.com/app-developer-resources.aspx

The link above should replace the currently linked URL below for the DOM element <a class="list-group-item"> on http://transitfeeds.com/p/marta/118.

http://www.itsmarta.com/developers/data-sources/marta-bus-gtfs-realtime.aspx

**Comment by HendX** [comment]
Thanks, updated.
