### ISSUE TITLE
CATA Michigan: No Feed Access Info is saved for this feed

### ISSUE THREAD

**Issue by akinhwan** [TransitFeeds/TransitFeeds-Public#258]
Cata Trip Updates   http://transitfeeds.com/p/capital-area-transportation-authority/504

has no feed access info...Include link below
https://www.cata.org/About/Doing-Business-with-CATA/Developer-Resources

**Comment by HendX** [comment]
Thanks, I've updated this and their other gtfs-rt feeds.
