### ISSUE TITLE
VIA San Antonio GTFS-Realtime Feeds

### ISSUE THREAD

**Issue by kencon** [TransitFeeds/TransitFeeds-Public#259]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY:  **United States**

- [ ] REGION: **Texas**

- [ ] CITY: **San Antonio**

- [ ] DIRECT DOWNLOAD URL: 
   **Vehicle Positions**: http://gtfs.viainfo.net/vehicle/vehiclepositions.pb
   **Trip Updates**: http://gtfs.viainfo.net/tripupdate/tripupdates.pb
   **Alerts**: http://gtfs.viainfo.net/alert/alerts.pb
   **Combined Feed**: http://gtfs.viainfo.net/gtfs-realtime/trapezerealtimefeed.pb
  
- [ ] FEED ACCESS INFO: http://viaprimo.com/Opportunities/DevLicense.aspx

- [ ] This feed is reliably updated: **YES**

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions): **YES**

**Comment by HendX** [comment]
Thanks @kencon, added here: https://transitfeeds.com/p/via-metropolitan-transit
