### ISSUE TITLE
RIPTA GTFS-Realtime Feeds

### ISSUE THREAD

**Issue by kencon** [TransitFeeds/TransitFeeds-Public#260]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: **United States**

- [ ] REGION: **Rhode Island**

- [ ] CITY: **Providence**

- [ ] DIRECT DOWNLOAD URL:
  **Vehicle Positions:**http://realtime.ripta.com:81/api/vehiclepositions?format=gtfs.proto
  **Trip Updates:**http://realtime.ripta.com:81/api/tripupdates?format=gtfs.proto
  **Service Alerts:**http://realtime.ripta.com:81/api/servicealerts?format=gtfs.proto
  
- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions): **YES**
- [ ] FEED ACCESS INFO: http://www.ripta.com/mobile-applications
  There doesn't seem to be any reference to their Transit API page at all on their site.

- [ ] This feed is reliably updated: **YES**

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/rhode-island-public-transit-authority
