### ISSUE TITLE
Monterey-Salinas Transit GTFS-Realtime Feeds

### ISSUE THREAD

**Issue by kencon** [TransitFeeds/TransitFeeds-Public#262]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: **United States**

- [x] REGION: **California**

- [x] CITY: **Monterey**

- [x] DIRECT DOWNLOAD URL: 
**Vehicle Positions:** http://206.128.158.191/TMGTFSRealTimeWebService/Vehicle/VehiclePositions.pb
**Trip Updates:** http://206.128.158.191/TMGTFSRealTimeWebService/Alert/Alerts.pb
**Service Alerts:** http://206.128.158.191/TMGTFSRealTimeWebService/TripUpdate/TripUpdates.pb
  
- [x] FEED ACCESS INFO: http://mst.org/about-mst/developer-resources/

- [x] This feed is reliably updated: **YES**

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions): **YES**

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/monterey-salinas-transit
