### ISSUE TITLE
Metro St. Louis GTFS-Realtime Feeds

### ISSUE THREAD

**Issue by kencon** [TransitFeeds/TransitFeeds-Public#264]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: **United States**

- [x] REGION: **Missouri**

- [x] CITY: **St. Louis**

- [x] DIRECT DOWNLOAD URL: 
**Vehicle Positions:** http://www.metrostlouis.org/RealTimeData/StlRealTimeVehicles.pb
**Trip Updates:** http://www.metrostlouis.org/RealTimeData/StlRealTimeTrips.pb
  
- [x] FEED ACCESS INFO: http://www.metrostlouis.org/developer-resources/

- [x] This feed is reliably updated: **YES**

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions): **YES**

**Comment by HendX** [comment]
Thanks, added here:
https://transitfeeds.com/p/bi-state-development-agency

Also added the green line feed as a separate feed. Not sure why they separate that out one.
