### ISSUE TITLE
RU St.Petersburg GTFS

### ISSUE THREAD

**Issue by wadim1611** [TransitFeeds/TransitFeeds-Public#265]
COUNTRY: Russia
REGION: Saint Petersburg
CITY: Saint Petersburg
Realtime GTFS: 
http://transport.orgp.spb.ru/Portal/transport/internalapi/gtfs/realtime/vehicle
  This is the URL of the Realtime GTFS zip
GTFS:
http://transport.orgp.spb.ru/Portal/transport/internalapi/gtfs/feed.zip
FEED ACCESS INFO: http://transport.orgp.spb.ru/Portal/transport/internalapi/gtfs/
 This is a web page with more information about the feed (such as licensing or access instructions)

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/saint-petersburg/861

Can't add their trip updates, since it requires a vehicle parameter to work.
