### ISSUE TITLE
Danish Gtfs

### ISSUE THREAD

**Issue by Brha2009** [TransitFeeds/TransitFeeds-Public#266]
Labs.rejseplanen has moved to new webpage, i´m sending new link to GTFS

- [x] COUNTRY: Denmark

- [x] REGION: Europe

- [x] DIRECT DOWNLOAD URL: https://help.rejseplanen.dk/hc/da/article_attachments/115004855069/GTFS.zip

**Comment by HendX** [comment]
This link didn't work - points to a login page. Is login required now?
