### ISSUE TITLE
EMT Málaga GTFS feed

### ISSUE THREAD

**Issue by joseflorido** [TransitFeeds/TransitFeeds-Public#267]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [X] COUNTRY: SPAIN

- [X] REGION: ANDALUCÍA

- [X] CITY: MÁLAGA

- [X] DIRECT DOWNLOAD URL: http://joseflorido.com/emt_fixed.zip
  This is the URL of the GTFS zip
  
- [X] FEED ACCESS INFO: http://datosabiertos.malaga.eu/dataset/lineas-y-horarios-bus-google-transit
  This is a web page with more information about the feed (such as licensing or access instructions)

- [X] This feed is reliably updated

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)
The official feed is available at http://datosabiertos.malaga.eu/recursos/transporte/EMT/lineasYHorarios/google_transit.zip but it does not validate as GTFS (is missing the agency.txt file). So I made a script that everyday downloads their feed, fixes it, and hosts it, reliably, on my own server.

**Comment by HendX** [comment]
Thanks, added here: 
https://transitfeeds.com/p/empresa-malaguena-de-transportes/874

**Comment by fede843** [comment]
This fixed feed has not been updated since almost one year. Official source is way pass beyond that. Is there any plan to update it or another URL?
Best
