### ISSUE TITLE
Lane Transit District GTFS-Realtime Feeds

### ISSUE THREAD

**Issue by kencon** [TransitFeeds/TransitFeeds-Public#268]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: **United States**

- [x] REGION: **Oregon**

- [x] CITY: **Eugene**

- [x] DIRECT DOWNLOAD URL: 
**Vehicle Positions:** http://feed.ltd.org/gtfs-realtime/vehicle
**Trip Updates:** http://feed.ltd.org/gtfs-realtime/tripupdate
**Service Alerts:** http://feed.ltd.org/gtfs-realtime/alerts
  
- [x] FEED ACCESS INFO: http://oregon-gtfs.com/

- [x] This feed is reliably updated: **YES**

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions): Seem official but there's no documentation anywhere regarding them at all even though hosted on LTD's domain.

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/lane-transit-district
