### ISSUE TITLE
Nashville MTA GTFS-Realtime Feeds

### ISSUE THREAD

**Issue by kencon** [TransitFeeds/TransitFeeds-Public#269]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: **United States**

- [x] REGION: **Tennessee**

- [x] CITY: **Nashville**

- [x] DIRECT DOWNLOAD URL: 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Alerts :**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://transitdata.nashvillemta.org/TMGTFSRealTimeWebService/alert/alerts.pb

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Trip Updates:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://transitdata.nashvillemta.org/TMGTFSRealTimeWebService/tripupdate/tripupdates.pb

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Vehicle Positions:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://transitdata.nashvillemta.org/TMGTFSRealTimeWebService/vehicle/vehiclepositions.pb
  
- [x] FEED ACCESS INFO: http://www.nashvillemta.org/Nashville-MTA-Developer-FAQs.asp

- [x] This feed is reliably updated: **YES**

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions): **YES**

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/nashville-mta
