### ISSUE TITLE
Get Feed data via API

### ISSUE THREAD

**Issue by satheeshvkumar** [TransitFeeds/TransitFeeds-Public#27]
I see that an API is given to see the live feed. But the API which says "getLatestFeedVersion" asks to input key and feed id, here I'm not able to figure out from where would I get the feed id. I did work with "getFeedVersions" response which has a tag named as id. I tried to input this value in "getLiveFeedVersion" URL but error is thrown back saying invalid input. Could you please lemme know from where can I get the feed id. Also can you tell me if this is possible for any feed we can browse from the home page

**Comment by HendX** [comment]
Hmmm - the method you suggested sounds correct; use the getFeedVersions call to determine the ID.

You can then add that value (e.g. feed=[ID]) onto the getLiveFeedVersion call.

For example:

http://api.transitfeeds.com/v1/getFeedVersions?key=[YOURKEY]&feed=chattanooga-area-regional-transportation-authority/360

If that doesn't work, please post on this thread the URL you tried to access (without your API key)

Thanks!

Quentin

**Comment by satheeshvkumar** [comment]
Got it, my bad. I was only entering the numeric id only and ignored the characters. I tried with the above URL and got the feed. But I have another doubt, I see that you are providing feeds for NYC Real Time Estimates as well, but I do not see it in the api results for "getFeedVersions". Is the API only for some selected feeds?

**Comment by HendX** [comment]
You can only get GTFS feeds at this stage - The site isn't archiving real-time data. It's high on the todo list, but for now you'll need to go directly to the MTA to get ongoing updates of their real-time data. It should be linked from http://transitfeeds.com/p/mta

**Comment by athrayee** [comment]
I tried with the following URL to access the NYC Real Time feed

api.transitfeeds.com/v1/getLatestFeedVersion?key=[mykey]&feeed=mta/420

and I get the following error.

{"status":"MISSINGINPUT","ts":1441392282,"results":{"input":"feed"}}

could you help me with this. I thing I doing the ID wrong but I am not sure where I can get the ID. I followed the link you have in the previous response and I replaced it with what I saw when I looked at the realtime source from NYC GTFS in browser.
