### ISSUE TITLE
Valley Metro Phoenix Light Rail GTFS-Realtime Feeds

### ISSUE THREAD

**Issue by kencon** [TransitFeeds/TransitFeeds-Public#272]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: **United States**

- [x] REGION: **Arizona**

- [x] CITY: **Phoenix**

- [x] DIRECT DOWNLOAD URL: 
&nbsp;&nbsp;&nbsp; **Vehicle Positions:** http://routes.valleymetro.org/api/vehicles
&nbsp;&nbsp;&nbsp; **Trip Updates:** http://routes.valleymetro.org/api/tripupdates
&nbsp;&nbsp;&nbsp; **Service Alerts:** http://routes.valleymetro.org/api/alerts
  
- [x] FEED ACCESS INFO: http://routes.valleymetro.org/api

- [x] This feed is reliably updated: **YES**

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions): **YES**

**Comment by HendX** [comment]
Added: https://transitfeeds.com/p/valley-metro
