### ISSUE TITLE
Kingston ON Realtime+ Main URL Change

### ISSUE THREAD

**Issue by useless2764** [TransitFeeds/TransitFeeds-Public#274]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: Canada

- [x] REGION: Ontario

- [x] CITY: Kingston

- [ ] DIRECT DOWNLOAD URL: 
http://kingston.metrolinx.tmix.se/gtfs/gtfs.zip

Service Alerts: http://kingston.metrolinx.tmix.se/gtfs-realtime/alerts.pb
Trip Updates: http://kingston.metrolinx.tmix.se/gtfs-realtime/tripupdates.pb
Vehicle Positions: http://kingston.metrolinx.tmix.se/gtfs-realtime/vehicleupdates.pb
  
- [ ] FEED ACCESS INFO: https://www.cityofkingston.ca/documents/10180/144997/GIS_OpenDataLicense.pdf/72f5a9ac-afbc-4fe3-959d-9111c9393bfa

- [X] This feed is reliably updated

- [X] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks, all updated: https://transitfeeds.com/p/city-of-kingston
