### ISSUE TITLE
Amazon SLU shuttle GTFS

### ISSUE THREAD

**Issue by zacs** [TransitFeeds/TransitFeeds-Public#275]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: US

- [x] REGION: Washington

- [x] CITY: Seattle

- [x] DIRECT DOWNLOAD URL: https://sea-shuttles.com/gtfs.zip
  
- [x] FEED ACCESS INFO: https://sea-shuttles.com/?site=desktop

- [x] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/amazon/882
