### ISSUE TITLE
gbrail.info / ATOC not updated since 24 June

### ISSUE THREAD

**Issue by eoghanmurray** [TransitFeeds/TransitFeeds-Public#276]
Looks like the gtfs feed at http://www.gbrail.info/gtfs.zip hasn't been updated in 4 weeks.
Is there a status indicator / error message for why the latest feed hasn't appeared?

With thanks!

**Comment by HendX** [comment]
Looks like the source feed hasn't updated. I'm not sure why.

**Comment by eoghanmurray** [comment]
Thanks @HendX - the ultimate source for the feed is http://data.atoc.org/data-download which has been updated since 24th June. Is the code that converts that feed to GTFS open?  I've since switched to using data.atoc.org directly so if there's anything I can do to get the gbrail.info feed working again let me know where I can hack on code etc.

**Comment by stevevance** [comment]
@eoghanmurray Are you using the Timetable Feed `http://data.atoc.org/system/files/ttis674.zip`? That's CIF format, not GTFS, right?

**Comment by eoghanmurray** [comment]
Ya, that's CIF - I'm using this now: https://github.com/open-track/dtd2mysql#convert-to-gtfs

**Comment by eoghanmurray** [comment]
This also has more regularly updated CIF data:
https://dtdportal.atocrsp.org/ 

I've written the following to automate the download & extraction of the feeds to database (no GTFS conversion):
https://github.com/GoPixie/rdg-to-db
