### ISSUE TITLE
NJ Transit GTFS-realtime data contains invalid field name "6"

### ISSUE THREAD

**Issue by mpEsri** [TransitFeeds/TransitFeeds-Public#278]
Feed source at https://transitfeeds.com/p/nj-transit/703/source
has invalid field name "6" in trip_update causing the GTFS text parser to fail.

Here's the sample data:

header {
  gtfs_realtime_version: "1.0"
  incrementality: FULL_DATASET
  timestamp: 1501900795
}
entity {
  id: "T1009"
  is_deleted: false
  trip_update {
    trip {
      trip_id: "107"
      start_time: "18:28:00"
      start_date: "20170804"
      schedule_relationship: SCHEDULED
      route_id: "2"
      6: 1 <------------- this is an invalid field?
    }
..

**Comment by HendX** [comment]
This is likely a custom field, which is allowed by the spec.

Note that you shouldn't really be parsing this data, since it's just a representation of the raw protocol buffer. If you want the data, you should use the protobuf directly.

**Comment by AkhilNairAmey** [comment]
@HendX Could you give me a hint of how to listen to the protobuf? I'm having real trouble finding where this is being sourced from.  Any help would be appreciated.
