### ISSUE TITLE
issue with Brisbane Translink real time data feed

### ISSUE THREAD

**Issue by lydiahoang** [TransitFeeds/TransitFeeds-Public#279]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: _Australia__

- [ ] REGION: ______Brisbane________________

- [ ] CITY: ____Brisbane__________________

- [ ] DIRECT DOWNLOAD URL: http://transitfeeds.com/p/translink/74
  This is the URL of the GTFS zip
  
- [ ] FEED ACCESS INFO: https://
  This is a web page with more information about the feed (such as licensing or access instructions)

- [ ] This feed is reliably updated

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by lydiahoang** [comment]
Hi, when I click on the above link, I get an HTTP Error 500: 
![error 500](https://user-images.githubusercontent.com/26017943/29048410-bbc4be34-7c13-11e7-8e1a-94a048a57030.PNG)

**Comment by HendX** [comment]
Not sure what's going wrong here - I just checked and the page is loading for me.

**Comment by HendX** [comment]
Actually - I see what's going wrong here - will try to fix (it's not currently occurring but may occur again)

**Comment by lydiahoang** [comment]
Thanks - that would be great if you could.
Kind RegardsLydia


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Quentin Zervaas <notifications@github.com> Date: 8/08/2017  11:45 AM  (GMT+10:00) To: TransitFeeds/TransitFeeds-Public <TransitFeeds-Public@noreply.github.com> Cc: Lydia Hoang <lydia.hoang@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [TransitFeeds/TransitFeeds-Public] issue with Brisbane Translink real time data feed (#279) 
Actually - I see what's going wrong here - will try to fix (it's not currently occurring but may occur again)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TransitFeeds/TransitFeeds-Public","title":"TransitFeeds/TransitFeeds-Public","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TransitFeeds/TransitFeeds-Public"}},"updates":{"snippets":[{"icon":"PERSON","message":"@HendX in #279: Actually - I see what's going wrong here - will try to fix (it's not currently occurring but may occur again)"}],"action":{"name":"View Issue","url":"https://github.com/TransitFeeds/TransitFeeds-Public/issues/279#issuecomment-320826550"}}}
