### ISSUE TITLE
Incorrect special character escaping in URLs

### ISSUE THREAD

**Issue by MKuranowski** [TransitFeeds/TransitFeeds-Public#281]
This one will be a bug report.

In Warsaw, trip_ids use the  `/` character.

All the links to trip views (like from [trip list of a route](http://transitfeeds.com/p/ztm-warszawa/720/latest/route/1/20170810)) escape `/` with `%2F`, but this escaping does not work, [like here](http://transitfeeds.com/p/ztm-warszawa/720/latest/trip/T%2FTP-NAR%2FDS%2F16.27__)
<img width="1189" alt="Incorrect escaping" src="https://user-images.githubusercontent.com/16469272/29142272-bd9cc618-7d51-11e7-84fc-425abf174a5e.png">

Instead, if I replace `%2F` with `/`, everything works fine, [like here](http://transitfeeds.com/p/ztm-warszawa/720/latest/trip/T/TP-NAR/DS/16.27__):
<img width="1217" alt="correct escaping" src="https://user-images.githubusercontent.com/16469272/29142330-ecf54bc4-7d51-11e7-9bd8-881824f43110.png">

**Comment by HendX** [comment]
Thanks - I've made a change which should fix this. Please let mw know if you notice anything off.
