### ISSUE TITLE
Bloomington Indiana feed location changed

### ISSUE THREAD

**Issue by laurahaley** [TransitFeeds/TransitFeeds-Public#282]
The hosted location for the Bloomington Indiana GTFS feed file has changed from http://bloomington.in.gov/transit/gtfeed/GoogleTransitFeed.zip to https://data.bloomington.in.gov/dataset/5aca3228-b81b-4572-a45c-b05a30053949/resource/16145a82-0959-4922-93ae-14dcee02950c/download/googletransitfeed.zip.  The feed has also been updated

Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: USA

- [ ] REGION: Indiana

- [ ] CITY:  Bloomington

- [ ] DIRECT DOWNLOAD URL: https://data.bloomington.in.gov/dataset/5aca3228-b81b-4572-a45c-b05a30053949/resource/16145a82-0959-4922-93ae-14dcee02950c/download/googletransitfeed.zip
  
- [ ] FEED ACCESS INFO: https://data.bloomington.in.gov/dataset/bloomington-transit-gtfs-data

- [  ] This feed is reliably updated: Yes

- [  ] This is an official feed (we try not to include unofficial feeds, but may make exceptions): Yes

**Comment by HendX** [comment]
Thanks, updated.
