### ISSUE TITLE
DC Circulator Feed

### ISSUE THREAD

**Issue by ehabebeid** [TransitFeeds/TransitFeeds-Public#284]
The DC Circulator and the DC Streetcar have been both removed from WMATA's transit feeds. The new feeds are produced by the District Department of Transportation.

- [x] COUNTRY: United States

- [x] REGION: District of Columbia

- [x] CITY: Washington, DC

- [x] DIRECT DOWNLOAD URL: http://circulatordashboard.dc.gov/circulatordata/gtfs/dc-circulator.zip
  
- [x] FEED ACCESS INFO: http://dccirculator.com/developer-resources/

- [x] This feed is reliably updated: **YES**

- [x] This is an official feed **YES**

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/wmata

**Comment by ehabebeid** [comment]
Hi!

Please list all three feeds under District of Columbia, as opposed to WMATA. The Circulator and Streetcar feeds are now under WMATA.
