### ISSUE TITLE
DC Streetcar Feed

### ISSUE THREAD

**Issue by ehabebeid** [TransitFeeds/TransitFeeds-Public#285]
The DC Circulator and the DC Streetcar have been both removed from WMATA's transit feeds. The new feeds are produced by the District Department of Transportation.

- [x] COUNTRY: United States

- [x] REGION: District of Columbia

- [x] CITY: Washington, DC

- [x] DIRECT DOWNLOAD URL: http://circulatordashboard.dc.gov/circulatordata/gtfs/dc-streetcar.zip
  
- [ ] FEED ACCESS INFO: Not yet available

- [x] This feed is reliably updated: **YES**

- [x] This is an official feed **YES**

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/wmata
