### ISSUE TITLE
https://api.transitfeeds.com/v1/getLatestFeedVersion is not giving any content.

### ISSUE THREAD

**Issue by HimaChitalia** [TransitFeeds/TransitFeeds-Public#286]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: USA__________

- [ ] REGION: NJ______________________

- [ ] CITY:EDISON ______________________

- [x ] DIRECT DOWNLOAD URL: https://transitfeeds.com/p/nj-transit/408/latest
  This is the URL of the GTFS zip
  
- [ x] FEED ACCESS INFO: https://api.transitfeeds.com/v1/getLatestFeedVersion?key=[MY_KEY]&feed=nj-transit%2F408%2Flatest

  This is a web page with more information about the feed (such as licensing or access instructions)

- [ x] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HimaChitalia** [comment]
Hi, 

I am trying to get the latest feed of nj-transit through url https://api.transitfeeds.com/v1/getLatestFeedVersion?key=[MY_KEY]&feed=nj-transit%2F408%2Flatest but Somehow it is not responding any content. I looked at the feed and it is available at  https://transitfeeds.com/p/nj-transit/408/latest

I also tried https://api.transitfeeds.com/v1/getLatestFeedVersion?key=[MY_KEY]&feed=nj-transit%2F408%2F20170811 but it is also not responding!


I am not sure how to exactly get that content!

**Comment by HendX** [comment]
Hi @HimaChitalia - just remove "/latest" from the ID. The ID value should be "nj-transit/408"
