### ISSUE TITLE
Weekendbus HUNGARY

### ISSUE THREAD

**Issue by petitetowb** [TransitFeeds/TransitFeeds-Public#287]
- [X] COUNTRY: HUNGARY

- [X] REGION: Pest county

- [X] CITY: Csömör, Budapest, Kistarcsa, Nagytarcsa, Pécel

- [X] DIRECT DOWNLOAD URL: http://apps.weekendbus.hu/gtfs/google_transit.zip
  
- [X] FEED ACCESS INFO: free to use

- [X] This feed is reliably updated

- [X] This is an official feed

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/weekendbus/887
