### ISSUE TITLE
GTFS feed for Wiener Linien, Vienna, Austria

### ISSUE THREAD

**Issue by robertharm** [TransitFeeds/TransitFeeds-Public#289]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: Austria

- [x] REGION: Vienna

- [x] CITY: Vienna

- [x] DIRECT DOWNLOAD URL: https://go.gv.at/l9gtfs
  This is the URL of the GTFS zip
  
- [x] FEED ACCESS INFO: https://www.data.gv.at/katalog/dataset/ab4a73b6-1c2d-42e1-b4d9-049e04889cf0
  This is a web page with more information about the feed (such as licensing or access instructions)

- [x] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/stadt-wien/888
