### ISSUE TITLE
Add SWU data

### ISSUE THREAD

**Issue by jhermsmeier** [TransitFeeds/TransitFeeds-Public#29]
SWU Nahverkehr Ulm/Neu-Ulm, Germany
http://www.swu.de/tr/privatkunden/swu-nahverkehr/gtfs-daten.html

**Comment by HendX** [comment]
Thanks - I've registered via their form, so I'll need to wait on their reply before I can access and add the data.

**Comment by jhermsmeier** [comment]
Cool, thanks! Yeah having to register to get to the data is a bit... annoying.

**Comment by HendX** [comment]
Added here: http://transitfeeds.com/p/swu-verkehr-gmbh
