### ISSUE TITLE
Piedmont Authority for Regional Transportion (PART), URL Change

### ISSUE THREAD

**Issue by mvhone** [TransitFeeds/TransitFeeds-Public#291]
Please update the entry for [PART](http://transitfeeds.com/p/piedmont-authority-for-regional-transportation/538)

- [x] COUNTRY: US

- [x] REGION: NC

- [x] CITY: Greensboro

- [x] DIRECT DOWNLOAD URL: http://demopro.nationalrtap.org/admin/GTFSzipFiles/3842/google_transit.zip
    
- [x] FEED ACCESS INFO: http://www.partnc.org/part-gtfs-exchange/

- [x] This feed is reliably updated: Updated quarterly

- [x] This is an official feed: I am employed by PART and responsible for this feed

**Comment by HendX** [comment]
Thanks, updated
