### ISSUE TITLE
Livermore Tri-Valley update

### ISSUE THREAD

**Issue by 3vivekb** [TransitFeeds/TransitFeeds-Public#292]
http://transitfeeds.com/p/livermore-amador-valley-transit-authority/701
This is an update to the previous location.  This place has up to date feeds.

- [x] DIRECT DOWNLOAD URL: 
I'm not sure how to get the direct URL but it is at this location:
http://www.wheelsbus.com/about/developers/

  
- [x] FEED ACCESS INFO: https://
  This is a web page with more information about the feed (such as licensing or access instructions)
http://www.wheelsbus.com/about/developers/

- [ ] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by stevevance** [comment]
The URL is `http://www.wheelsbus.com/wp-content/uploads/2017/08/google_transit.zip?read_comply=`

**Comment by HendX** [comment]
Thanks, updated.
