### ISSUE TITLE
Add GTFS Data for Boise, Idaho, USA

### ISSUE THREAD

**Issue by VRTTransit** [TransitFeeds/TransitFeeds-Public#293]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them

- [x] COUNTRY: United States

- [x] REGION: Idaho

- [x] CITY: Boise

- [x] DIRECT DOWNLOAD URL: http://www.valleyregionaltransit.org/GTFS/VRT_Transit1.zip
  
- [ ] FEED ACCESS INFO: 

- [x] This feed is reliably updated: Updated Quarterly

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions): Yes

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/valleyride/889
