### ISSUE TITLE
Riverside Transit Agency GTFS-RT

### ISSUE THREAD

**Issue by bbodenmiller** [TransitFeeds/TransitFeeds-Public#294]
Realtime data for existing Riverside Transit Agency entry

- [x] COUNTRY: USA

- [x] REGION: California

- [x] CITY: Riverside

- [x] DIRECT DOWNLOAD URL: https://rtabus.com/gtfsrt/
  
- [x] FEED ACCESS INFO: https://www.riversidetransit.com/index.php/riding-the-bus/transit-apps

- [x] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by rickkaz** [comment]
Direct download URL is https://rtabus.com/gtfsrt/

**Comment by bbodenmiller** [comment]
@HendX this is ready for processing now. Also when proceed can close https://github.com/TransitFeeds/TransitFeeds-Public/issues/327 also.

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/riverside-transit-agency
