### ISSUE TITLE
Burlington Transit real time feeds

### ISSUE THREAD

**Issue by useless2764** [TransitFeeds/TransitFeeds-Public#295]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: Canada

- [x] REGION: Ontario

- [x] CITY: Burlington

- [ ] FEED ACCESS INFO: https://
  This is a web page with more information about the feed (such as licensing or access instructions)

- [X] This feed is reliably updated

- [X] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

Service Alerts: http://opendata.burlington.ca/gtfs-rt/GTFS_ServiceAlerts.pb
Trip Updates: http://opendata.burlington.ca/gtfs-rt/GTFS_TripUpdates.pb
Vehicle Positions: http://opendata.burlington.ca/gtfs-rt/GTFS_VehiclePositions.pb

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/burlington-transit
