### ISSUE TITLE
Add StarMetro to list of feeds

### ISSUE THREAD

**Issue by christrillium** [TransitFeeds/TransitFeeds-Public#296]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: __United States____________________

- [ ] REGION: ______Florida________________

- [ ] CITY: ___Tallahassee___________________

- [ ] DIRECT DOWNLOAD URL: 
http://data.trilliumtransit.com/gtfs/starmetro-fl-us/starmetro-fl-us.zip
  
- [ ] FEED ACCESS INFO: https://
  This is a web page with more information about the feed (such as licensing or access instructions)

- [ ] This feed is reliably updated 
YES

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)
YES

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/starmetro/885
