### ISSUE TITLE
TANK GTFS Feed - New server

### ISSUE THREAD

**Issue by fbusofsky** [TransitFeeds/TransitFeeds-Public#297]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: ____USA__________________

- [ ] REGION: ______SOUTH________________

- [ ] CITY: __FT WRIGHT____________________

- [ ] DIRECT DOWNLOAD URL: ftp://66.42.202.68/GTFS-NKU/google_transit.zip
  This is the URL of the GTFS zip
  
- [ ] FEED ACCESS INFO: https://
  This is a web page with more information about the feed (such as licensing or access instructions)

- [ ] This feed is reliably updated

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by stevevance** [comment]
This URL isn't accessible. 

I get the error 
````
530 USER CANNOT LOG IN, HOME DIRECTORY INACCESSIBLE. .
````

**Comment by HendX** [comment]
Replaced by #340
