### ISSUE TITLE
Citymapper GTFS-Realtime

### ISSUE THREAD

**Issue by nathan9** [TransitFeeds/TransitFeeds-Public#299]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: United Kingdom

- [x] REGION: London

- [x] CITY: London

- [x] DIRECT DOWNLOAD URL: http://opendata.citymapper.com/uk-london/trip_updates.pbf
  This is the URL of the GTFS-Realtime PBF
  
- [x] FEED ACCESS INFO: https://citymapper.com/smartbus/opendata
  This is a web page with more information about the feed (such as licensing or access instructions)

- [x] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/citymapper
