### ISSUE TITLE
Add feeds for Switzerland

### ISSUE THREAD

**Issue by jhermsmeier** [TransitFeeds/TransitFeeds-Public#30]
http://gtfs.geops.ch/

**Comment by HendX** [comment]
Thanks - I tried importing the full data set but the sheer amount of data made my server struggle. I'm going to leave this job open for now but I'll need to reassess the best way to approach importing this data.

**Comment by dragoon** [comment]
Now available from the official SBB-supported protal: https://opentransportdata.swiss/en/dataset/timetable-2017-gtfs

**Comment by HendX** [comment]
Thanks @dragoon, added here: https://transitfeeds.com/p/sbb-cff-ffs

**Comment by stebazzi** [comment]
yes, but is better http://gtfs.geops.ch/. Try it and note the differences.
In this one the data are sorted by different agency name. Aren't all in Acency name "SBB"
Is not correct the official dataset.
Many thanks.

**Comment by dragoon** [comment]
Geops was already proposed initially in this thread. While it contains correct agency attribution in the data, it also treats every trip as a new route, which is conceptually wrong and results in a really heavy routes.txt file.

**Comment by stebazzi** [comment]
You are right, I know.
Both aren't correct...
