### ISSUE TITLE
Rhode Island Public Transit Authority needs data update

### ISSUE THREAD

**Issue by kerri-hicks** [TransitFeeds/TransitFeeds-Public#300]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [X] COUNTRY: USA

- [X] REGION: Rhode Island

- [X] CITY: None, agency name RIPTA

- [X] DIRECT DOWNLOAD URL: https://www.ripta.com/stuff/contentmgr/files/0/3cda81dfa140edbe9aae214b26245b4a/files/google_transit.zip
  This is the URL of the GTFS zip
  
- [X] FEED ACCESS INFO: https://www.ripta.com/mobile-applications
  This is a web page with more information about the feed (such as licensing or access instructions)

- [X] This feed is reliably updated

- [X] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks, updated. It appears that this URL might change though, whereas the old one looked like a static one.
