### ISSUE TITLE
Edmonton Transit System Real Time Alerts Feed

### ISSUE THREAD

**Issue by useless2764** [TransitFeeds/TransitFeeds-Public#303]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [X] COUNTRY: Canada
- [X] REGION: Alberta

- [X] CITY: Edmonton

- [X] DIRECT DOWNLOAD URL:  Alerts: https://data.edmonton.ca/download/rqaa-jae6/application%2Foctet-stream
  
- [ ] FEED ACCESS INFO: 
- [X] This feed is reliably updated

- [X] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

also the other real time feeds are showing a last updated time of 55 weeks ago for whatever reason

**Comment by HendX** [comment]
Thanks, added: https://transitfeeds.com/p/edmonton-transit-system/890
