### ISSUE TITLE
Add KVV (Karlsruhe), Germany

### ISSUE THREAD

**Issue by robbi5** [TransitFeeds/TransitFeeds-Public#306]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: Germany

- [x] REGION: Baden-Württemberg

- [x] CITY: Karlsruhe

- [x] DIRECT DOWNLOAD URL: http://213.144.24.66/GTFS/google_transit.zip
  This is the URL of the GTFS zip
  
- [x] FEED ACCESS INFO: https://www.kvv.de/fahrplanauskunft/fahrplanauskunft-efa/opendata.html
  This is a web page with more information about the feed (such as licensing or access instructions)

- [x] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/karlsruher-verkehrsverbundes/896
