### ISSUE TITLE
Niagara Region Feed

### ISSUE THREAD

**Issue by useless2764** [TransitFeeds/TransitFeeds-Public#325]
Feed url is now https://maps.niagararegion.ca/googletransit/NiagaraRegionTransit.zip

**Comment by stevevance** [comment]
This new feed URL has only 7 operators, but the previous feed has 8 operators. Niagara Parks Commission WeGo is missing from this new feed URL.

**Comment by useless2764** [comment]
doesnt seem like wego data exists anywhere (even on google maps itself) anymore, otherwise

**Comment by useless2764** [comment]
still needs an update, feed has the wego lines in it now though

**Comment by HendX** [comment]
Just updated to 
https://maps.niagararegion.ca/googletransit/NiagaraRegionTransit.zip
