### ISSUE TITLE
SEPTA: 69th Street Parent Station Missing

### ISSUE THREAD

**Issue by crhallberg** [TransitFeeds/TransitFeeds-Public#328]
In the Septa system, "stops" feed, the stop 69th St Transportation Center - NHSL (32206) is missing its parent station data, which should be 69th Street Transportation Center (31034) as all the other 69th Street station parts are.

- [x] COUNTRY: United States
- [x] REGION: North East
- [x] CITY: Philadelphia
- [x] DIRECT DOWNLOAD URL: http://transitfeeds.com/p/septa/263/latest/download  
- [x] FEED ACCESS INFO: http://transitfeeds.com/p/septa/263/latest
- [x] This feed is reliably updated
- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by jpiorkowski** [comment]
Please turn to the source and maintainers of the data: https://github.com/septadev/GTFS
