### ISSUE TITLE
Add Danish GTFS data

### ISSUE THREAD

**Issue by HendX** [TransitFeeds/TransitFeeds-Public#33]
Available from here:
http://labs.rejseplanen.dk/labs/data__brug/tilmelding_for_samarbejdspartnere/

I tried to register, but the form didn't work and it didn't throw back errors. I suspect it was a data validation issue on the phone number or zip code.

**Comment by joriswu** [comment]
I registered successfully and get access to a 20 MB  GTFS feed.

http://labs.rejseplanen.dk/files/GTFS/GTFS.zip

**Comment by HendX** [comment]
Thanks @joriswu, added here: https://transitfeeds.com/p/rejseplanen/705

(may not be populated at time of writing this though - will be shortly though)
