### ISSUE TITLE
Add GTFS Static for I-RIDE Trolley (Orlando - Florida - USA)

### ISSUE THREAD

**Issue by wideanglefocus** [TransitFeeds/TransitFeeds-Public#338]
COUNTRY: United States of America

REGION: Southeast

STATE: Florida

CITY: Orlando

DIRECT DOWNLOAD URL: https://
  https://data.omnimodal.io/gtfs/iride-fl-us/iride-fl-us.zip

I-RIDE TROLLEY URL:  http://www.iridetrolley.com/
 
This feed is reliably updated

This is an official feed.

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/i-ride-trolley/909
