### ISSUE TITLE
TANK Feed URL Change

### ISSUE THREAD

**Issue by fbusofsky** [TransitFeeds/TransitFeeds-Public#340]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: _____USA_________________

- [ ] REGION: ________KY______________

- [ ] CITY: ______Fort Wright________________

- [ ] DIRECT DOWNLOAD URL: https://www.tankbus.org/Portals/tankbus/gtfs/tank-google-transit.zip
  This is the URL of the GTFS zip
  
- [ ] FEED ACCESS INFO: https://
  This is a web page with more information about the feed (such as licensing or access instructions)

- [ ] This feed is reliably updated

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Done, thanks!
