### ISSUE TITLE
TAN feed URL changed (Nantes, France)

### ISSUE THREAD

**Issue by vdng9338** [TransitFeeds/TransitFeeds-Public#341]
The URL for TAN's GTFS feed changed in September.

- [ ] COUNTRY: France

- [ ] REGION: Pays de la Loire

- [ ] CITY: Nantes

- [ ] DIRECT DOWNLOAD URL: https://data.nantes.fr/fileadmin/data/datastore/nm/mobilite/24440040400129_NM_TAN_00253/ARRETS_HORAIRES_CIRCUITS_TAN_2017_2018_gtfs.zip (still a zip in a zip)
  
- [ ] FEED ACCESS INFO: https://data.nantes.fr/donnees/detail/arrets-horaires-et-circuits-tan-2017-2018/

- [ ] This feed is reliably updated
- [ ] This is an official feed

**Comment by vdng9338** [comment]
Nantes Métropole updated their open data website, resulting in yet another URL change:

DIRECT DOWNLOAD URL: https://data.nantesmetropole.fr/api/datasets/1.0/244400404_tan-2017-2018-arrets-horaires-circuits/alternative_exports/arrets_horaires_circuits_tan_2017_2018_zip/ (which is now a standard GTFS zip file!)

FEED ACCESS INFO: https://data.nantesmetropole.fr/explore/dataset/244400404_tan-2017-2018-arrets-horaires-circuits/information/

**Comment by vdng9338** [comment]
Yet another URL change:
DIRECT DOWNLOAD URL: [https://data.nantesmetropole.fr/explore/dataset/244400404_tan-arrets-horaires-circuits/files/16a1a0af5946619af621baa4ad9ee662/download/](https://data.nantesmetropole.fr/explore/dataset/244400404_tan-arrets-horaires-circuits/files/16a1a0af5946619af621baa4ad9ee662/download/)
FEED ACCESS INFO: [https://data.nantesmetropole.fr/explore/dataset/244400404_tan-arrets-horaires-circuits/information/](https://data.nantesmetropole.fr/explore/dataset/244400404_tan-arrets-horaires-circuits/information/)

**Comment by HendX** [comment]
Thanks - yea ideally the link would remain the same, but oh well!
