### ISSUE TITLE
Samtrans FeedUpdate

### ISSUE THREAD

**Issue by 3vivekb** [TransitFeeds/TransitFeeds-Public#357]
The feed location for [Samtrans](http://transitfeeds.com/p/samtrans/144) needs to be updated.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: ______________________
United States

- [x] REGION: ______________________
California

- [x] CITY: ______________________
l/68-san-francisco-ca-usa
- [x] DIRECT DOWNLOAD URL: https://
  This is the URL of the GTFS zip
  http://www.samtrans.com/Assets/GTFS/samtrans/ST-GTFS.zip?v=01092018
or 
http://www.samtrans.com/Assets/GTFS/samtrans/ST-GTFS.zip

- [x] FEED ACCESS INFO: 
http://www.samtrans.com/Developer.html

- [x] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Thanks, updated.
