### ISSUE TITLE
Updated feed location for USA-AZ-Phoenix-Valley Metro

### ISSUE THREAD

**Issue by pleitman** [TransitFeeds/TransitFeeds-Public#359]
The GTFS feed for Valley Metro (Phoenix-AZ-USA) has been changed. Note that the old feed link is still live but out-of-date (https://www.phoenix.gov/publictransitsite/Documents/google_transit.zip). The old feed access site (https://www.phoenix.gov/publictransit/developers-portal) notes that the feed source has changed.

The other feeds (Service Alerts, Trip Updates and Vehicle Positions) may also need to be updated. They are here: https://phoenixopendata.com/organization/public-transit

Below are the details for the new GTFS feed location.

- [ x ] COUNTRY: UNITED STATES

- [ x ] REGION: ARIZONA

- [ x ] CITY: PHOENIX

- [ x ] DIRECT DOWNLOAD URL: https://phoenixopendata.com/dataset/3eae9a4a-98b9-40c8-8df7-8c00c1756235/resource/28ccc0a5-49c8-495c-b91f-193de5ce2cb7/download/googletransit.zip
  This is the URL of the GTFS zip
  
- [ x ] FEED ACCESS INFO: https://phoenixopendata.com/dataset/valley-metro-bus-schedule/resource/28ccc0a5-49c8-495c-b91f-193de5ce2cb7
  This is a web page with more information about the feed (such as licensing or access instructions)

- [ x ] This feed is reliably updated

- [ x ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Updated.
