### ISSUE TITLE
Add Suffolk County Transit (SCT) on Long Island/in New York

### ISSUE THREAD

**Issue by RES2773** [TransitFeeds/TransitFeeds-Public#36]

**Comment by HendX** [comment]
Thanks @RES2773, do you have a link to their GTFS feed? I couldn't find it on their web site or on the transit-admin.511ny.org site either

**Comment by RES2773** [comment]
Sorry, I actually meant another agency, but I looked and it's already up
there. While we're on the subject, I checked and they don't have one. I am
not good with these things, do you know if there is someone I could ask to
make it?

On Sunday, July 5, 2015, Quentin Zervaas <notifications@github.com> wrote:

> Thanks @RES2773 <https://github.com/RES2773>, do you have a link to their
> GTFS feed? I couldn't find it on their web site or on the
> transit-admin.511ny.org site either
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TransitFeeds/TransitFeeds-Public/issues/36#issuecomment-118682800>
> .
>


-- 
Sent from Gmail Mobile

**Comment by HendX** [comment]
You'd have to contact the agency directly and ask them. Typically if they offer Google Transit as a trip planning option, then they will have a GTFS feed already available. But whether or not they make it available to people other than Google is the question...

**Comment by RES2773** [comment]
I have never dealt with something as weird as this before! Suffolk County
Transit is on Hopstop, where you CAN view all of the stops and times, but
it is not on google transit. To make it even a bigger pain, they do not
have an e-mail contact, just a phone number and a mailing adress, which (a)
the person on the phone may not know what I'm talking about or know someone
who will, and it will take forever to have a conversation via snail mail. I
am almost completely certain that they do not have a feed. I don't really
know what else to do.

P.S. I have contacted NICE about the n47, but I am fairly sure it still
exists, considering it is still in the latest schedule, and on their route
list and interactive map.

Thanks again!

**Comment by BRJ06** [comment]
I am also looking for this data. Is this available now? If not, strongly recommend the agency could make their network available to public.
