### ISSUE TITLE
Taiwan>5 cities  of Central Taiwan 

### ISSUE THREAD

**Issue by gean0516b5** [TransitFeeds/TransitFeeds-Public#362]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: R.O.C

- [x] REGION: Taiwan

- [x] CITY: 5 cities  of Central Taiwan 

- [x] DIRECT DOWNLOAD URL: 
                                                     http://23.99.120.200/bnb/api/gtfs/gtfs_ch_20180306.zip
                                                     http://23.99.120.200/bnb/api/gtfs/gtfs_ml_20180306.zip
                                                     http://23.99.120.200/bnb/api/gtfs/gtfs_tc_20180306.zip
                                                     http://23.99.120.200/bnb/api/gtfs/gtfs_nt_20180306.zip
                                                     http://23.99.120.200/bnb/api/gtfs/gtfs_yl_20180306.zip
                                                     
  These are #the URL of the GTFS zip
  
- [ ] FEED ACCESS INFO: http://23.99.120.200/bnb/gtfs
  This is a web page with more information about the feed (such as licensing or access instructions)
   
- [ ] This feed is reliably updated

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by gean0516b5** [comment]
Hi! we want to contribute the central Taiwan GTFS data , and had submitted the download URL for five months. We can't find the feeding data in feed page (https://transitfeeds.com/feeds) . Could anyone show  what we went wrong? thanks a lot !!

**Comment by HendX** [comment]
Apologies - I've emailed you.

Ideally we want a separate entry for each data source, so the specific provider name and/or location name would be most useful.

Also, we need a static URL, so when the data is updated, it still uses the same URL.
