### ISSUE TITLE
Question: How often are existing feeds refreshed?

### ISSUE THREAD

**Issue by 3vivekb** [TransitFeeds/TransitFeeds-Public#363]
How often is an existing feed refreshed?

How often would you say, scan vta.org for an updated gtfs feed?  And post the new feed?

**Comment by HendX** [comment]
12-24 hours

**Comment by 3vivekb** [comment]
It's odd - the (VTA gtfs)[http://transitfeeds.com/p/vta/45] has been updated (I believe on Feb 15th) yet your fetch routine missed the update.  Hmm.

**Comment by HendX** [comment]
It is updated now. You can see where it's fetching from by mousing over the "official download url" link.
