### ISSUE TITLE
Victoria Clipper URL updated

### ISSUE THREAD

**Issue by zacs** [TransitFeeds/TransitFeeds-Public#369]
## UPDATE EXISTING FEED:

Existing GTFS is out of date. The below URL will be unchanged regardless of any future updates, and is a bit easier to revise by the community. 

Please fill out the following if an existing feed has a new download URL:

- [x] URL ON TRANSITFEEDS: https://transitfeeds.com/p/the-victoria-clipper/800
- [x] NEW DOWNLOAD URL (direct link): https://github.com/zacs/victoriaclipper-gtfs/raw/master/build/clipper.zip

If application:

- [x] NEW FEED INFORMATION URL: https://github.com/zacs/victoriaclipper-gtfs/

**Comment by HendX** [comment]
Thanks, updated.
