### ISSUE TITLE
Add Barrie Transit GTFS Data

### ISSUE THREAD

**Issue by danmackay** [TransitFeeds/TransitFeeds-Public#37]
terms at http://www.barrie.ca/Living/Getting%20Around/BarrieTransit/Pages/Barrie-GTFS.aspx
direct link: http://transit.cityofbarriesites.com/files/google_transit.zip
real time positioning: http://transit.cityofbarriesites.com/files/gtfrealtime.bin

**Comment by HendX** [comment]
Thanks - added here:

http://transitfeeds.com/p/barrie-transit
