### ISSUE TITLE
MBTA Direction Error

### ISSUE THREAD

**Issue by DamianBurgos** [TransitFeeds/TransitFeeds-Public#370]
If you at all the routes, the Direction is wrong, for example, the Route 32 going towards Wolcott Sq and Cleary Sq it shows it as an Inbound. The route 39 going towards Back Bay shows outbound when its suppose to be Inbound.

**Comment by HendX** [comment]
Thanks - but this is a feed level issue that would need to be fixed by MBTA.

**Comment by DamianBurgos** [comment]
It is perfectly fine with the MBTA , I have an API and it shows it correctly for me.
