### ISSUE TITLE
Tyler Shuttle

### ISSUE THREAD

**Issue by pilot0674** [TransitFeeds/TransitFeeds-Public#372]
## NEW FEEDS:

To submit **new** feeds, visit [Submit a Feed](https://transitfeeds.com/submit).

Note that if you click on **Submit a Feed** on a location or provider details page, the location and provider will be automatically populated.

At this time we can only accept static, unchanging URLs. Maintenance of dynamic URLs is proving too difficult and time-consuming.

## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL ON TRANSITFEEDS: _________________________
- [ ] NEW DOWNLOAD URL (direct link): _________________________

If application:

- [ ] NEW FEED INFORMATION URL: _________________________

**Comment by 3vivekb** [comment]
There isn't any information in this issue.
