### ISSUE TITLE
Add GTFS Static + Realtime for Sanford Trolley (Sanford - Florida - USA)

### ISSUE THREAD

**Issue by wideanglefocus** [TransitFeeds/TransitFeeds-Public#373]
NEW FEED INFORMATION URLS for Sanford Trolley, Sanford, Florida, USA.

Schedule (GTFS Static): https://data.omnimodal.io/gtfs/sanfordcommunity-fl-us/sanfordcommunity-fl-us.zip

Trip Updates (GTFS Realtime): http://sanfordcra.omnimodal.io:8080/api/v1/key/<api_key>/agency/1/command/gtfs-rt/tripUpdates

Vehicle Positions (GTFS Realtime): http://sanfordcra.omnimodal.io:8080/api/v1/key/<api_key>/agency/1/command/gtfs-rt/vehiclePositions

**Comment by HendX** [comment]
Done. Although - is that your API key embedded in the URL?

**Comment by HendX** [comment]
I've hidden the direct links for now, but they're still being used on the site. Can you create a new API key specifically for TransitFeeds and email it to us?

**Comment by wideanglefocus** [comment]
We have created a new API key and emailed it to you. Thanks!

**Comment by HendX** [comment]
Done now, thanks.
