### ISSUE TITLE
UPDATE EXISTING FEED: NYMTA Busses

### ISSUE THREAD

**Issue by colinmcglynn** [TransitFeeds/TransitFeeds-Public#375]
## UPDATE EXISTING FEED: NYMTA Busses

For the following feeds the download URLs haven't changed, a new version is available from the 'Official Download URL' but that version isn't listed on TransitFeeds

http://transitfeeds.com/p/mta/80
http://transitfeeds.com/p/mta/81
http://transitfeeds.com/p/mta/82
http://transitfeeds.com/p/mta/83
http://transitfeeds.com/p/mta/84

Thanks!

**Comment by colinmcglynn** [comment]
Since I filed the issue, it looks like all of the feeds are on the latest version except for http://transitfeeds.com/p/mta/80

**Comment by HendX** [comment]
So this is all ok now?

**Comment by colinmcglynn** [comment]
yup all good now!
