### ISSUE TITLE
Update existing feeds: MBTA

### ISSUE THREAD

**Issue by paulswartz** [TransitFeeds/TransitFeeds-Public#376]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [x] URL ON TRANSITFEEDS: http://transitfeeds.com/p/mbta
- [x] NEW DOWNLOAD URL (direct link):
    - GTFS: https://cdn.mbta.com/MBTA_GTFS.zip
    - Service Alerts: https://cdn.mbta.com/realtime/Alerts.pb
    - Trip Updates: https://cdn.mbta.com/realtime/TripUpdates.pb
    - Vehicle Positions: https://cdn.mbta.com/realtime/VehiclePositions.pb

**Comment by HendX** [comment]
Updated, apologies for the delay.
