### ISSUE TITLE
Update existing feed: Szczecin, Poland official feed

### ISSUE THREAD

**Issue by tengl** [TransitFeeds/TransitFeeds-Public#377]
It seems to be https now, no redirect...

- [ ] URL ON TRANSITFEEDS: http://transitfeeds.com/p/zditm-szczecin/587
- [ ] NEW DOWNLOAD URL (direct link): https://www.zditm.szczecin.pl/rozklady/GTFS/latest/google_gtfs.zip

**Comment by HendX** [comment]
Updated
