### ISSUE TITLE
Malaga wrong data

### ISSUE THREAD

**Issue by fede843** [TransitFeeds/TransitFeeds-Public#378]
Data for Malaga (https://transitfeeds.com/p/empresa-malaguena-de-transportes/874) is being fetched from http://datosabiertos.malaga.eu/recursos/transporte/EMT/lineasYHorarios/google_transit.zip.
As it was stated in https://github.com/TransitFeeds/TransitFeeds-Public/issues/267 at its creation, it is not a valid GTFS. Former given source is outdated too.

**Comment by fede843** [comment]
A new txt formated file has been published http://datosabiertos.malaga.eu/dataset/lineas-y-horarios-bus-google-transit

Still agency.txt is missing. Sent an email. It might get fixed

**Comment by HendX** [comment]
Updated to 
http://datosabiertos.malaga.eu/recursos/transporte/EMT/lineasYHorarios/google_transit_txt.zip

Let me know if there's any further issues
