### ISSUE TITLE
New Url for Denmark GTFS

### ISSUE THREAD

**Issue by niklascp** [TransitFeeds/TransitFeeds-Public#379]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL ON TRANSITFEEDS: http://transitfeeds.com/p/rejseplanen/705
- [ ] NEW DOWNLOAD URL (direct link): http://www.rejseplanen.as/GTFS_New.zip

**Comment by HendX** [comment]
Thanks, updated.
