### ISSUE TITLE
New URL's for Kingston Transit

### ISSUE THREAD

**Issue by useless2764** [TransitFeeds/TransitFeeds-Public#383]
https://api.cityofkingston.ca/gtfs/gtfs.zip

Vehicle Positions: https://api.cityofkingston.ca/gtfs-realtime/vehicleupdates.pb

Trip updates: https://api.cityofkingston.ca/gtfs-realtime/tripupdates.pb

Service alerts: https://api.cityofkingston.ca/gtfs-realtime/alerts.pb

**Comment by HendX** [comment]
Thanks, updated.
