### ISSUE TITLE
Access Denied to Luxembourg OpenOV stop_times.txt

### ISSUE THREAD

**Issue by jedi-marcus** [TransitFeeds/TransitFeeds-Public#384]
Hi,

The following endpoint returns an "Access Denied" whereas other on the same level work out ok:
https://transitfeeds.com/p/openov/621/latest/download/stop_times.txt

To reproduce:
https://transitfeeds.com/p/openov/621/latest/file/stop_times.txt
-> View File

**Comment by HendX** [comment]
We've removed access to stop_times.txt because they are costly in data transfer. You can access the data instead by downloading the full GTFS file.
