### ISSUE TITLE
Turkey-Kocaeli

### ISSUE THREAD

**Issue by yunustekel** [TransitFeeds/TransitFeeds-Public#388]
- [x] COUNTRY: Turkey
- [x] CITY: Kocaeli
- [x] DIRECT DOWNLOAD URL: http://kocaeli.bel.tr/webfiles/userfiles/files/birimler/bilgi-islem-dairesi-baskanligi/kocaeli-gtfs.zip

- [x]  This is an official feed

**Comment by yunustekel** [comment]
http://kocaeli.bel.tr/webfiles/userfiles/files/birimler/bilgi-islem-dairesi-baskanligi/kocaeli-gtfs.zip

> NEW FEEDS:
> To submit new feeds, visit Submit a Feed.
> Note that if you click on Submit a Feed on a location or provider details page, the location and provider will be automatically populated.
> At this time we can only accept static, unchanging URLs. Maintenance of dynamic URLs is proving too difficult and time-consuming.
> UPDATE EXISTING FEED:
> Please fill out the following if an existing feed has a new download URL:
> 
> 
>   
>     
>    URL ON TRANSITFEEDS: _________________________
> 
>   
>     
>    NEW DOWNLOAD URL (direct link): _________________________
> 
> If application:
> 
> 
>   
>     
>    NEW FEED INFORMATION URL: http://kocaeli.bel.tr/webfiles/userfiles/files/birimler/bilgi-islem-dairesi-baskanligi/kocaeli-gtfs.zip

**Comment by HendX** [comment]
Thanks - added here:
https://transitfeeds.com/p/kocaeli-buyuksehir-belediyesi/964

Apologies for the delay.

**Comment by TeodoraB21** [comment]
It is not available anymore

**Comment by myunustekel** [comment]
COUNTRY: Turkey

  CITY: Kocaeli

  DIRECT DOWNLOAD URL:  COUNTRY: Turkey

  CITY: Kocaeli

  DIRECT DOWNLOAD URL: http://kocaeli.bel.tr/webfiles/userfiles/files/birimler/bilgi-islem-dairesi-baskanligi/kocaeli-gtfs.zip

  This is an official feed
