### ISSUE TITLE
Add Belgian GTFS data

### ISSUE THREAD

**Issue by pietercolpaert** [TransitFeeds/TransitFeeds-Public#39]
It's over here:

http://gtfs.irail.be

**Comment by HendX** [comment]
Thanks @pietercolpaert, I'll aim to get it loaded onto TransitFeeds early next week

**Comment by HendX** [comment]
STIB / MIVB here: http://transitfeeds.com/p/societe-des-transports-intercommunaux-de-bruxelles

**Comment by HendX** [comment]
NMBS / SNCB here: http://transitfeeds.com/p/societe-nationale-des-chemins-de-fer-belges

**Comment by HendX** [comment]
TEC here: http://transitfeeds.com/p/societe-regionale-wallonne-du-transport

**Comment by HendX** [comment]
De Lijn here: http://transitfeeds.com/p/vlaamse-vervoersmaatschappij-de-lijn
