### ISSUE TITLE
Accepting new feeds?

### ISSUE THREAD

**Issue by linusnorton** [TransitFeeds/TransitFeeds-Public#392]
I've been trying to submit a new feed via the website but I've not heard anything and there doesn't seem to be a feedback process. I've also contacted support via email but not heard anything - are you still accepting new feeds?

**Comment by linusnorton** [comment]
I have a replacement for the UK rail feed (which stopped over a year ago) and also a few different feeds for UK bus

**Comment by fede843** [comment]
Oh, that would be great. Do you mean you have a replacement for this missing source http://gtfs.gbrail.info/gtfs.zip ?
How frequent is the update process?
Best!

**Comment by linusnorton** [comment]
Yes, I have a direct replacement that's updated daily.

**Comment by HendX** [comment]
Updated, should process shortly.

**Comment by linusnorton** [comment]
thanks

**Comment by linusnorton** [comment]
@HendX was there a problem processing the feed?

**Comment by HendX** [comment]
Sorry - I know we're not as responsive as possible currently, but we're working on improving things.

**Comment by HendX** [comment]
@linusnorton Why's that? Is this not correct?

https://transitfeeds.com/p/association-of-train-operating-companies/284/latest

**Comment by linusnorton** [comment]
Sorry my mistake, I was checking the wrong place.
