### ISSUE TITLE
New GTFS URL for SCAT (Sarasota, FL, USA)

### ISSUE THREAD

**Issue by barbeau** [TransitFeeds/TransitFeeds-Public#396]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [x] URL ON TRANSITFEEDS: http://transitfeeds.com/p/sarasota-county-area-transit/376
- [x] NEW DOWNLOAD URL (direct link): ftp://ftp.scgov.net/pub/scat/SCATGTFS.zip

**Comment by HendX** [comment]
Thanks, updated.

**Comment by barbeau** [comment]
Thanks @HendX!
