### ISSUE TITLE
Poland > Wrocław URL changed

### ISSUE THREAD

**Issue by gtfs0** [TransitFeeds/TransitFeeds-Public#398]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL ON TRANSITFEEDS: http://transitfeeds.com/p/mpk-wroc-aw/663
- [ ] NEW DOWNLOAD URL (direct link): https://www.wroclaw.pl/open-data/dataset/rozkladjazdytransportupublicznegoplik_data/resource/0aea29fc-6553-43e1-98ff-322f7e2c491f

If application:

- [ ] NEW FEED INFORMATION URL: https://www.wroclaw.pl/open-data/dataset/rozkladjazdytransportupublicznegoplik_data

**Comment by HendX** [comment]
Updated
