### ISSUE TITLE
Kuopio GTFS URL Changed

### ISSUE THREAD

**Issue by gtfs0** [TransitFeeds/TransitFeeds-Public#399]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL ON TRANSITFEEDS: http://transitfeeds.com/p/city-of-kuopio/731
- [ ] NEW DOWNLOAD URL (direct link): http://karttapalvelu.kuopio.fi/google_transit/google_transit.zip

If application:

- [ ] NEW FEED INFORMATION URL: http://vilkku.kuopio.fi/sv/reaaliaikapalvelut

**Comment by HendX** [comment]
Updated
