### ISSUE TITLE
New URL for SWU, Germany

### ISSUE THREAD

**Issue by robbi5** [TransitFeeds/TransitFeeds-Public#400]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [x] URL ON TRANSITFEEDS: https://transitfeeds.com/p/swu-verkehr-gmbh/512
- [x] NEW DOWNLOAD URL (direct link): https://gtfs.swu.de/daten/SWU.zip
- [x] NEW FEED INFORMATION URL: https://www.swu.de/privatkunden/service/mobilitaet/gtfs-daten/

**Comment by HendX** [comment]
Thanks, updated.
