### ISSUE TITLE
Guelph Transit Real Time URLS

### ISSUE THREAD

**Issue by useless2764** [TransitFeeds/TransitFeeds-Public#402]
Alerts: http://transitgtfs.guelph.ca:9780/TMGTFSRealTimeWebService/Alert/Alerts.pb
Trip Updates: http://transitgtfs.guelph.ca:9780/TMGTFSRealTimeWebService/TripUpdate/TripUpdates.pb
Vehicle Locations: http://transitgtfs.guelph.ca:9780/TMGTFSRealTimeWebService/Vehicle/VehiclePositions.pb

**Comment by HendX** [comment]
Thanks, added here: https://transitfeeds.com/p/guelph-transit
