### ISSUE TITLE
Add new agencies, especially in SF Area

### ISSUE THREAD

**Issue by calvintam236** [TransitFeeds/TransitFeeds-Public#43]
When I googled for GTFS data, I found this site: https://code.google.com/p/googletransitdatafeed/wiki/PublicFeeds

There are several agencies I noticed are not listed in the transit feeds. There are more are not in the database.
1. Rio Vista Delta
2. Fairfield and Suisun Transit
3. Santa Clara Valley Transportation Authority

**Comment by HendX** [comment]
Hi @calvintam236 - thanks for the request. Notes below:

1. Just added here: http://transitfeeds.com/p/rio-vista-delta-breeze
2. Already available: http://transitfeeds.com/p/fairfield-and-suisun-transit
3. Already available: http://transitfeeds.com/p/vta
