### ISSUE TITLE
Api to query the feed

### ISSUE THREAD

**Issue by fcasarsa** [TransitFeeds/TransitFeeds-Public#48]
Hi, 

maybe i did not found it, is there an API to query the archive? i specifically need the data that is presented in this page but programmatically:

http://transitfeeds.com/p/gruppo-torinese-trasporti/51/latest/route/379/20150915

Thanks.

**Comment by HendX** [comment]
The API doesn't allow querying in this manner. It allows you to determine when there is an update for a given agency.

You can access that data by downloading the GTFS directly and parsing/using the data in that.

**Comment by fcasarsa** [comment]
It is really a shame!!! 

Is this software closed source? 

Thanks.

**Comment by HendX** [comment]
It would be good to offer this, but we have limited server capabilities and resources.
