### ISSUE TITLE
A few more feeds

### ISSUE THREAD

**Issue by mldickens** [TransitFeeds/TransitFeeds-Public#51]
State College, PA: http://www.catabus.com/data/index.html
Charleston, SC: http://data.trilliumtransit.com/gtfs/carta-sc-us/carta-sc-us.zip
Greensboro/Winston-Salem, NC: http://www.partnc.org/part-gtfs-exchange/
Des Moines, IA: https://www.ridedart.com/business-center/developer-resources (requires login)

**Comment by HendX** [comment]
Thanks. Gradually adding them.

Here's State College: http://transitfeeds.com/p/catabus

**Comment by HendX** [comment]
Charleston: http://transitfeeds.com/p/charleston-area-regional-transportation-authority

**Comment by HendX** [comment]
Greensboro: http://transitfeeds.com/p/piedmont-authority-for-regional-transportation

**Comment by HendX** [comment]
Des Moines: http://transitfeeds.com/p/des-moines-area-regional-transit-authority
