### ISSUE TITLE
Add Buenos Aires Subte

### ISSUE THREAD

**Issue by dnohales** [TransitFeeds/TransitFeeds-Public#57]
I'd like to add the Buenos Aires City underground transportation system (subte).

Data information web page:
http://data.buenosaires.gob.ar/dataset/subte-gtfs

GTFS archive:
https://recursos-data.buenosaires.gob.ar/ckan2/subte-gtfs/subte-gtfs.zip

Thanks!

**Comment by HendX** [comment]
Thanks for the info. Added here: http://transitfeeds.com/p/subterraneos-de-buenos-aires
