### ISSUE TITLE
Missing feed for GO Transit

### ISSUE THREAD

**Issue by gboudreau** [TransitFeeds/TransitFeeds-Public#60]
For some reason, the Union-Pearson bus route has its own GTFS file:
http://www.gotransit.com/publicroot/gtfs/google_transit_UP.zip
Should be added under http://transitfeeds.com/p/go-transit

Info URL (for both GTFS for Go Transit): http://www.gotransit.com/publicroot/en/schedules/DeveloperResources.aspx

Thanks.

**Comment by HendX** [comment]
Thanks! Added here: http://transitfeeds.com/p/go-transit/543
