### ISSUE TITLE
Get list of feed ids API

### ISSUE THREAD

**Issue by milesizzo** [TransitFeeds/TransitFeeds-Public#61]
It would be hugely beneficial if one could access a full list of all feed ids (with meta information, similar to what is provided in getFeedVersions) via the API. Would that be possible?

**Comment by HendX** [comment]
I agree - out of interest, how do you want to discover the feed IDs? For example, by location, or just a list of everything, or what?

**Comment by milesizzo** [comment]
I'd be happy with a big list of everything available, then use other API queries to get more information about each feed (eg. list all versions, etc.). I guess it could also be useful to have a way to look up all feeds active in a particular geo bounds?

**Comment by HendX** [comment]
Thanks. Agree this would be useful. Will try to find time soon for it.

**Comment by mldickens** [comment]
It would be great to be able to pull down a list of feed IDs from one country!

**Comment by HendX** [comment]
This has now been added. More info at http://transitfeeds.com/api

Basically, there are 2 new calls:

1) getLocations
2) getFeeds

You can filter the list in getFeeds by a location ID (and optionally include all sub-locations too). You can retrieve location IDs from the getLocations call.

Using getFeeds, you can determine feed IDs so they can be passed to the other calls.

Please let me know if there are any issues with this.

**Comment by mldickens** [comment]
This looks great! It doesn't look like the overall locations pull up
everything underneath though. If I use "United States" as the location
(id=31) I get no results. If I use United Kingdom (id=177) I get the one
operator that has United Kingdom as its location, but not the other
operator that is in the UK.

Matthew Dickens
202-834-0828

**Comment by HendX** [comment]
You'll need to include descendants=1 as part of the request

**Comment by mldickens** [comment]
Got it - awesome!

Matthew Dickens
