### ISSUE TITLE
BogoMap as a transit provider

### ISSUE THREAD

**Issue by angoca** [TransitFeeds/TransitFeeds-Public#62]
BogoMap is a project that aims to collect open data of the public transportation system in Bogota. They have collected many elements like routes and bus stops and they have published the data as open.

The site is: bogomap.co and the data is at: https://github.com/BogoMap/bogomap/tree/master/src/csv

**Comment by HendX** [comment]
Thanks @angoca - I've added it here:

http://transitfeeds.com/p/bogomap
