### ISSUE TITLE
new Florida agencies - please add

### ISSUE THREAD

**Issue by schurnsi** [TransitFeeds/TransitFeeds-Public#63]
7 new data feeds for Florida, please add to TransitFeeds.

Baytown Trolley: http://data.trilliumtransit.com/gtfs/baytowntrolley-fl-us/baytowntrolley-fl-us.zip

Sunshine Bus Company: http://data.trilliumtransit.com/gtfs/sunshinebuscompany-fl-us/sunshinebuscompany-fl-us.zip

Citrus County Transit: http://data.trilliumtransit.com/gtfs/citruscounty-fl-us/citruscounty-fl-us.zip

The Hernando Express: http://data.trilliumtransit.com/gtfs/thehernandoexpress-fl-us/thehernandoexpress-fl-us.zip

SunTran: http://data.trilliumtransit.com/gtfs/suntran-fl-us/suntran-fl-us.zip

Emerald Coast Rider: http://data.trilliumtransit.com/gtfs/okaloosacountytransit-fl-us/okaloosacountytransit-fl-us.zip

Escambia County Area Transit: http://data.trilliumtransit.com/gtfs/ecat-fl-us/ecat-fl-us.zip

**Comment by barbeau** [comment]
+1! :)

**Comment by HendX** [comment]
Thanks - will do soon - will update here once done.

**Comment by HendX** [comment]
These have all been added here:

http://transitfeeds.com/l/74-florida-usa

**Comment by barbeau** [comment]
Thanks @HendX!
