### ISSUE TITLE
germany VBB update

### ISSUE THREAD

**Issue by rpdcorbion** [TransitFeeds/TransitFeeds-Public#73]
The VBB GTFS is out of date on transitfeed, the new one for 2016 is here : http://www.vbb.de/de/datei/GTFS_VBB_Nov2015_Dez2016.zip 

Can you update the feed?

Thanks

**Comment by HendX** [comment]
Thanks - I've updated this. They make this feed quite hard to automatically download with their JavaScript based redirects (as well as lack of static URL).
