### ISSUE TITLE
Valley Metro (Phoenix) Data Location

### ISSUE THREAD

**Issue by mldickens** [TransitFeeds/TransitFeeds-Public#75]
Looks like they changed the location of their GTFS file on us. It is now at the City of Phoenix open data site:
https://www.phoenix.gov/publictransit/developers-portal

Link to the actual file is at the bottom of that page.

**Comment by HendX** [comment]
Thanks - updated here: http://transitfeeds.com/p/valley-metro

**Comment by colinmcglynn** [comment]
@HendX New GTFS is available from https://www.phoenix.gov/publictransit/developers-portal but it hasn't been updated on TransitFeeds yet.

**Comment by HendX** [comment]
Thanks @colinmcglynn, updated. I'm not sure why it didn't autoupdate, since I had the correct URL in there already.
