### ISSUE TITLE
Stop_times.txt warning for optional field

### ISSUE THREAD

**Issue by leanne63** [TransitFeeds/TransitFeeds-Public#76]
The following warning shows for the bi-state-development-agency feed:
`stop_times.txt: Unrecognised column in stop_times.txt: timepoint`

However, `timepoint` is actually an acceptable field in stop_times.txt. It's just optional.

**Comment by HendX** [comment]
Thanks for pointing this out - previously it was an experimental field only. I was unaware it was now part of the spec.

Existing feeds on the site will continue to show this warning, but newly-processed feeds will no longer flag it as a warning.
