### ISSUE TITLE
City of Shimada GTFS feed has started.

### ISSUE THREAD

**Issue by aalt** [TransitFeeds/TransitFeeds-Public#78]
City of Shimada, Local Government's Voluntary Operation Bus GTFS has started.

OpenTransit
http://opentrans.it/feed/gtfs/5724160613416960/gtfs.zip
OpenDataFund
http://opendata.fund/shimada_city/gtfs/gtfs.zip

**Comment by HendX** [comment]
Thanks - will update here when I've added it.

**Comment by aalt** [comment]
Thanks. I 'm looking forward adding. :+1:

**Comment by HendX** [comment]
Added here: http://transitfeeds.com/p/opentransit/588

**Comment by nikolauskrismer** [comment]
This might not be the right place (sorry, but I can not speak and/or read japanese and everything from opentrans.it is written in japanese), but I was just wondering that the two linked gtfs files are very different.

The feeds do not contain a calendar.txt file. This file is mandatory according to the [GTFS reference](https://developers.google.com/transit/gtfs/reference/) (as far as I understand it can be empty, but not missing).

However, more confusing is that the feed from OpenTransit (not the one from OpenDataFund) only uses a calendar_dates.txt file which only removes specific dates. So all in all we have no calendars and even from that "minimal set" entries are removed. Was adding dates using calendar_dates.txt intended? Then the exception_type to use is "1" and not "2".

Is this some kind of GTFS usage that I do not know of?
What does it mean then?
