### ISSUE TITLE
Burlington GTFS

### ISSUE THREAD

**Issue by gboudreau** [TransitFeeds/TransitFeeds-Public#79]
About: http://transitfeeds.com/p/burlington-transit/294

The GTFS below includes data up to 2016-01-31. The latest on Transitfeeds ends 2015-12-31.

URL:
http://www.burlington.ca/en/services-for-you/resources/Ongoing_Projects/Open_Data/Catalogue/GTFS_Data.zip

Source: http://cob.burlington.opendata.arcgis.com/

Thanks.

**Comment by HendX** [comment]
Thanks - I've just updated this.
