### ISSUE TITLE
Add Nancy GTFS data

### ISSUE THREAD

**Issue by MilleMiles** [TransitFeeds/TransitFeeds-Public#86]
Available from here:
http://opendata.grand-nancy.org/jeux-de-donnees/detail-dune-fiche-de-donnees/?tx_icsoddatastore_pi1[page]=3&tx_icsoddatastore_pi1[uid]=108&tx_icsoddatastore_pi1[returnID]=447

**Comment by HendX** [comment]
Thanks, added here:

http://transitfeeds.com/p/communaute-urbaine-du-grand-nancy
