### ISSUE TITLE
Trentino Italy GTFS data

### ISSUE THREAD

**Issue by Gooinski** [TransitFeeds/TransitFeeds-Public#94]
http://www.ttesercizio.it/TTEOpenData/

Trentino urban and extraurban GTFS feeds are available

**Comment by HendX** [comment]
Thanks! Added here: http://transitfeeds.com/p/trentino-trasporti-esercizio

**Comment by openmove** [comment]
Hi, 
I want to report that now the official website changed in 
https://trentinotrasporti.it/open-data/

the website ttesercizio.it is no longer maintained.
