### ISSUE TITLE
Wilmington, NC, Data Feed

### ISSUE THREAD

**Issue by YodasWs** [TransitFeeds/TransitFeeds-Public#97]
You can download the latest from Wave Transit in Wilmington, NC, [here](http://www.wavetransit.com/gtransit/google_transit.zip)

Thanks!
&mdash;Sam

**Comment by HendX** [comment]
Thanks @YodasWs - does that file work for you? I'm having trouble with it (the zip won't decompress)

**Comment by mldickens** [comment]
Zip worked for me, so I added it.

http://transitfeeds.com/p/wave-transit/633
