### ISSUE TITLE
Add more public feeds

### ISSUE THREAD

**Issue by YodasWs** [TransitFeeds/TransitFeeds-Public#98]
You can check for more public feeds through http://www.transitwiki.org/TransitWiki/index.php?title=Publicly-accessible_public_transportation_data

**Comment by HendX** [comment]
Thanks @YodasWs - I'm working to get more feeds on the site, but mostly it's a time constraint currently. Are there are on there specifically that are missing on here that you'd like added?

I'm looking to open up the site to more content editors soon, but I'm to improve some of the admin functionality to make this go more smoothly.

**Comment by HendX** [comment]
I'm going to close this in the absence of posts for specific feeds
