### ISSUE TITLE
SEPTA isn't consistently updating the feed on their website.

### ISSUE THREAD

**Issue by colinmcglynn** [TransitFeeds/TransitFeeds-Public#99]
TransitFeed is currently using http://www3.septa.org/developer/ but it hasn't been updated since December and the data is currently expired.

SEPTA is releasing new data to their Github repository so that may be a better source for you to use
https://github.com/septadev/GTFS/releases

**Comment by HendX** [comment]
Thanks @colinmcglynn, I've just fixed this and refreshed both the bus and rail feed.
